<?php 
$get = $this->get;
$params = $this->params;

$getLoginUserInformation = $this->getLoginUserInformation;

$record = $this->paginator; 
$totalrec = $this->totalrec;

$getAllUserInfo = $this->getAllUserInfo;
?>


<script type="text/javascript">
  function goback() {
    history.go(-1);
  }
</script>

<!-- fancybox start here -->
<script type="text/javascript" src="/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<script type="text/javascript">
	$(document).ready(function() {	
    $("a#view-details").fancybox({
      'transitionIn'	:	'elastic',
      'transitionOut'	:	'elastic',
      'width' : 800,
      'height' : 500,
      'speedIn'		:	600, 
      'speedOut'		:	200, 
      'overlayShow'	:	true
    });	
  });

 $(document).ready(function() {	
   $("a#showfarmerpopups").fancybox({
     'width' : "80%",
     'height' : "80%",
     'speedIn'		:	600, 
     'speedOut'		:	200, 
     'overlayShow'	:	true
   });	
 });	



</script> 

<div class="content">

  <div class="header">
    <h1 class="page-title">Contact Information Detail </h1>
  </div>
  <div class="breadcrumb">
    <div style="position:relative;">
      <ul class="imop">
        <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
        <li class="active">View Contact Information</li> 
      </ul>
      <?php if($params['type']=='sucess') { ?>
      <div class="alert alert-info">
        <button data-dismiss="alert" class="close" type="button">×</button>
        Field executive has been successfully updated
      </div>	
      <?php } ?>


    </div>
    <a href="javascript:void(0);" style="position:absolute; right:10px; top:5px; border: 1px solid; background-color: #4d5b76; color: #fff; padding:1px 6px; font-size:12px; font-weight:bold; display:block;" id="showuserlocation" class="iframe" onClick="goback();">Back</a>
  </div>
  <script>
    $(document).ready(function() {
      $('.breadcrumb').css({'width':(($(window).width())-270)+'px'});
      $(window).resize(function(){
       $('.breadcrumb').css({'width':(($(window).width())-270)+'px'}); 
     });
    });

    function getSearch(name, mobile, user, address,polling_both,under)
    {


      document.search.action="/capturedinfo/view-contact/name/"+name+"/mobile/"+mobile+"/user/"+user+"/address/"+address+"/polling_both/"+polling_both+"/under/"+under;  

      document.search.submit();  
    }
  </script>





  <style>
  .tableheading{
   background-color: #e2e2e2;
   color: #000;
   font-weight: bold;
   text-align: center;
   padding-bottom: 5px;
   border-bottom: 1px solid #cfcccc;
 }
 .txt_center{
   text-align:center !important;
 }
 .imop{
  margin:0px !important;
}


@media screen and (max-width: 480px) {

  #mobile {
    display:block;
  }

  #name {
    display:block;
  }

  #address {
    display:block;
  }

  #polling_both {
    display:block;
  }


  #searchbtn {
    display:block;
  }

}



}
}
</style>
<div class="container-fluid" style="padding-top:162px;">

  <!--- user filtor by role end -->

  <div class="row-fluid" style="margin-top:10px;">

    <div class="search-well" style="display:block;">
      <div  style="display: block;">
       <form class="form-inline" style="width:1000px; float: left;" name="search" method="post"  style="margin-bottom:10px;">


        <input type="text" name="name" id="name" placeholder="Search By Name..."  value="<?php if($params['name']){ echo $params['name'];  }?>" class="input-large" style="margin-right:20px">
        <input type="text" name="mobile" id="mobile"  placeholder="Search By Mobile No..." value="<?php if($params['mobile']){ echo $params['mobile'];  }?>" class="input-large" style="margin-right:20px">
        <input type="text" name="address" id="address"  placeholder="Search By Address..." value="<?php if($params['address']){ echo $params['address'];  }?>" class="input-large" style="margin-right:20px">

        <input type="text" name="polling_both" id="polling_both" placeholder="Search By Polling Both..." value="<?php if($params['polling_both']){ echo $params['polling_both'];  }?>" class="input-large" style="margin-right:20px" >
        <br><br>

        <select name="user" class="input-large" id="engineer" onchange="GetFarmerList(this.value)" style="margin-right:32px">
         <option  value =''>--Select Field User --</option>
         <?php foreach($getAllUserInfo as $key) { ?>
         <option  value ='<?php  echo $key['LoginID'] ?>'<?php if($params['user'] !='' && $params['user']==$key['LoginID']){echo ' selected="selected"';} ?>><?php  echo $key['StaffName'].'('.$key['LoginID'].')' ?></option>
         <?php  } ?>
       </select>

       <select name="under" class="input-large" id="under" onchange="GetFarmerList(this.value)" style="margin-right:32px" >
         <option  value =''>--Select Under--</option>
         <?php foreach($this->getUnderUserInfo as $key) { ?>
         <option  value ='<?php  echo $key['id'] ?>'<?php if($params['under'] !='' && $params['under']==$key['id']){echo ' selected="selected"';} ?>><?php  echo $key['under']; ?></option>
         <?php  } ?>  
       </select>
       <button type="button" onclick="getSearch(this.form.name.value, this.form.mobile.value, this.form.user.value, this.form.address.value, this.form.polling_both.value ,this.form.under.value)"  class="btn" id="searchbtn" style="position:relative; text-align:center; padding-left:22px;margin-right:32px"><span class="search"></span> Go</button>
     </form>
     <div  style="display: block;">

      <div>
        <div style="  display:block; width:15%; padding:11px; "></div>

      </div> 
    </div>

    <a href="/capturedinfo/view-contact/type/generate_contact/name/<?php  echo $params['name']; ?>/user/<?php  echo $params['user']; ?>/mobile/<?php  echo $params['mobile']; ?>/address/<?php  echo $params['address']; ?>/polling_both/<?php  echo $params['polling_both']; ?>/under/<?php  echo $params['under']; ?>" class="btn btn-primary" type="submit" style="margin-bottom: 5px;margin-top: 10px">Export In Excel</a>   
    <div class="well" style="overflow:scroll; height:auto;">

      <table class="table tablesorter">
        <thead>

         <tr><td colspan="13" class="tableheading">Contatct Information Detail</td></tr>
         <tr>
          <th>S.No.</th>
          <th>Name</th>
          <th>Identity</th>
          <th>Mobile</th>
          <th>Whatsapp No</th>
          <th>Polling Both Id</th>  
          <th>Availability</th>                                           
          <th>Date</th>
          <th>View Position</th>
          <th>View</th>  

        </tr>
      </thead>
      <tbody>
       <?php

       if($totalrec){
        $totalnum = $this->totalnum?$this->totalnum:1;
        $istart = ($totalnum-1) * 10;
        $i=$istart;
        foreach($record as $key=>$val){


         ?>
         <tr>
           <td><?php echo $i+1; ?></td>        
           <td><?php echo ucfirst($val['name']);?></td>

           <?php if($val['identity'] !=''){  ?>
           <td><a href="/capturedinfo/view-under/data/<?php echo $val['identity'];?>" class="iframe" id="view-details" title="View Details" style="background-color: #4d5b76;border: 1px solid; color: #fff;display: block;font-size: 9px;font-weight: bold;padding: 2px;float: left"><?php echo ucfirst($val['identity']); ?></a></td>

           <?php }else{ ?>
           <td><?php echo ucfirst($val['identity']); ?></td>
           <?php } ?>
           <td><?php echo ucfirst($val['mobile']);?></td>
           <td><?php echo ucfirst($val['whatsapp']);?></td>                                                            
           <td><?php echo ucfirst($val['polling_both']);?></td>
           <td><?php echo ucfirst($val['availiability']);?></td>
           <td><?php echo ucfirst($val['offline_sink_datetime']);?></td>
           <td>
            <?php if($val['add_by'] !='web'){ ?>
            <a class="iframe" id="showfarmerpopups" style="background-color: #4d5b76;border: 1px solid; color: #fff;display: block;font-size: 9px;font-weight: bold;padding: 2px;float: left;" href="/user/location/data/<?php echo $val['id'];?>">View Location
            </a>
            <?php   }else{
             echo '-';

             ?>

             <?php } ?>  
           </td>
           <td><a href="/user/view-detail/data/<?php echo md5($val['id']);?>/under/<?php echo $val['parent_user']; ?>" class="iframe" id="view-details" title="View Details" style="background-color: #4d5b76;border: 1px solid; color: #fff;display: block;font-size: 9px;font-weight: bold;padding: 2px;float: left">view</a></td>


           <?php  $i++; } } else { ?>  
           <tr><td colspan="8">Result not found.</td></tr>
           <?php } ?>

         </tbody>
       </table>
     </div>

     <!--Pagingnation Start-->
     <?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); } ?>
   </div>
 </div>
</div>


