<style>
li {list-style:none; color:#ed3237; font-size:13px;}
ul{margin:0px; padding:0px;}
</style>
<?php $form = $this->form;?>
    
<div class="row-fluid">
    <div class="dialog">
        <div class="block">
            <p class="block-heading">Forgot your password</p>
            <div class="block-body">
             <p style="color:red;"><?php echo $this->errorMessage;?></p>
                <form method="post" action="/index/forgotpassword">
                    <label>Mobile Number</label>
                     <?php echo $form->phone;?>
                     <input name="submit" class="btn btn-primary pull-left" value="Send" type="submit">
					 <p style="padding-left:220px;"><a href="/index">Sign in to your account</a> </p>
                    <div class="clearfix"></div>
					
                </form>
            </div>
        </div>
        
    </div>
</div>


