<?php 
$get = $this->get;
$params = $this->params;
//$allLands = $this->allLands;

$getLoginUserInformation = $this->getLoginUserInformation;

$record = $this->paginator; 
$totalrec = $this->totalrec;
//echo '<pre>';
//print_r($record);
//exit();
$getAllUserInfo = $this->getAllUserInfo;
?>

    
<script type="text/javascript">
function goback() {
    history.go(-1);
}
</script>

<!-- fancybox start here -->
<script type="text/javascript" src="/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<script type="text/javascript">
	$(document).ready(function() {	
				$("a#view-details").fancybox({
				'transitionIn'	:	'elastic',
				'transitionOut'	:	'elastic',
				'width' : 800,
				'height' : 500,
				'speedIn'		:	600, 
				'speedOut'		:	200, 
				'overlayShow'	:	true
				});	
			});
			
			$(document).ready(function() {	
					$("a#showfarmerpopups").fancybox({
					'width' : "80%",
					'height' : "80%",
					'speedIn'		:	600, 
					'speedOut'		:	200, 
					'overlayShow'	:	true
					});	
				});	


					
</script> 

<div class="content">
        
        <div class="header">
            <h1 class="page-title">Contact Information Detail </h1>
        </div>
        <div class="breadcrumb">
        <div style="position:relative;">
        <ul class="imop">
            <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
            <li class="active">View Contact Information</li> 
        </ul>
        <?php if($params['type']=='sucess') { ?>
		<div class="alert alert-info">
				<button data-dismiss="alert" class="close" type="button">×</button>
				Field executive has been successfully updated
		</div>	
		<?php } ?>
		
		
        </div>
        <a href="javascript:void(0);" style="position:absolute; right:10px; top:5px; border: 1px solid; background-color: #4d5b76; color: #fff; padding:1px 6px; font-size:12px; font-weight:bold; display:block;" id="showuserlocation" class="iframe" onClick="goback();">Back</a>
        </div>
<script>
$(document).ready(function() {
    $('.breadcrumb').css({'width':(($(window).width())-270)+'px'});
	$(window).resize(function(){
       $('.breadcrumb').css({'width':(($(window).width())-270)+'px'}); 
    });
});
</script>





<style>
.tableheading{
	background-color: #e2e2e2;
	color: #000;
	font-weight: bold;
	text-align: center;
	padding-bottom: 5px;
	border-bottom: 1px solid #cfcccc;
}
.txt_center{
	text-align:center !important;
}
.imop{
margin:0px !important;
}
</style>
        <div class="container-fluid" style="padding-top:162px;">

<!--- user filtor by role end --->

 <div class="row-fluid" style="margin-top:10px;">
                    
<div class="search-well">
<div class="form-inline">
	<form class="form-inline" style="width:1000px; float: left;" method="get" action="" style="margin-bottom:10px;">
            
            
		<input type="text" name="name" id="search" placeholder="Search By Name..." value="<?php if($params['name']){ echo $params['name'];  }?>" class="input-large">
                <input type="text" name="mobile" id="search" placeholder="Search By Mobile No..." value="<?php if($params['mobile']){ echo $params['mobile'];  }?>" class="input-large">
                <select name="user" class="input-large" id="engineer" onchange="GetFarmerList(this.value)" >
		   <option  value =''>--Select Field User--</option>
		   <?php foreach($getAllUserInfo as $key) { ?>
                   <option  value ='<?php  echo $key['LoginID'] ?>'<?php if($params['user'] !='' && $params['user']==$key['LoginID']){echo ' selected="selected"';} ?>><?php  echo $key['StaffName'].'('.$key['LoginID'].')' ?></option>
		   <?php  } ?>
		</select>
		<button type="submit" class="btn" id="searchbtn" style="position:relative; text-align:center; padding-left:22px;"><span class="search"></span> Go</button>
        </form>
    
<div style="  display:block; width:15%; padding:11px; ">
  
  
</div>
           
</div> 
</div>

 <a href="/capturedinfo/view-contact/type/generate_contact" class="btn btn-primary" type="submit" style="margin-bottom: 5px;">Export In Excel</a>   
<div class="well" style="overflow:scroll; height:auto;">
    
    <table class="table tablesorter">
      <thead>

	  <tr><td colspan="13" class="tableheading">Contatct Information Detail</td></tr>
        <tr>
        <th>S.No.</th>
                                            <th>Name</th>
                                            <th>Mobile</th>
                                            <th>Whatsapp No</th>
                                            <th>Polling Both Id</th>  
                                            <th>Availability</th>
                                            <th>User ID</th>  
                                            <th>Date</th>
                                            <th>View Position</th>
                                            <th>View</th>  

 </tr>
      </thead>
      <tbody>
       <?php
	   	
	if($totalrec){
          $i=1;
	  foreach($record as $key=>$val){
	    $users = new Application_Model_Care();
            $getUserNameByUserId= $users->getUserNameByUserId($val['user_id']);
        
         ?>
        <tr> 
           <td><?php echo $i; ?></td>        
                                                                <td><?php echo ucfirst($val['name']);?></td>
                                                                <td><?php echo ucfirst($val['mobile']);?></td>
                                                                <td><?php echo ucfirst($val['whatsapp']);?></td>                                                            
                                                                <td><?php echo ucfirst($val['polling_both']);?></td>
                                                                <td><?php echo ucfirst($val['availiability']);?></td>
                                                                <td><?php echo ucfirst($getUserNameByUserId['StaffName'].' ('.$val['user_id'].')');?></td>
                                                                <td><?php echo ucfirst($val['offline_sink_datetime']);?></td>
                                                                <td><a class="iframe" id="showfarmerpopups" style="background-color: #4d5b76;border: 1px solid; color: #fff;display: block;font-size: 9px;font-weight: bold;padding: 2px;float: left;" href="/user/location/data/<?php echo $val['id'];?>">View Location</a></td>
                                                                <td><a href="/user/view-detail/data/<?php echo md5($val['id']);?>" class="iframe" id="view-details" title="View Details" style="background-color: #4d5b76;border: 1px solid; color: #fff;display: block;font-size: 9px;font-weight: bold;padding: 2px;float: left">view</a></td>


           <?php  $i++; } } else { ?>  
	   <tr><td colspan="8">Result not found.</td></tr>
	   <?php } ?>

      </tbody>
    </table>
</div>

<!--Pagingnation Start-->
<?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); } ?>
	</div>
</div>
</div>
    
   
