<?php
        $record = $this->paginator; 
        $auth = Zend_Auth::getInstance();
        $authStorage = $auth->getStorage();
        $totalrec = $this->totalrec;
	$params = $this->params;
        $alltask = $this->AllTask;
       $result = $this->fqbdetailsbyid;
       $record = $this->getStaffNameAndMobileNo;
       //$first_names = array_column($result, 'fqb_no');

     //echo "<pre>"; print_r($params); die;
?>
<link rel="stylesheet" href="/css/datepicker/jquery.ui.all.css">


<script src="/js/jquery-1.8.3.js"></script>

<script type="text/javascript" src="/js/jquery.timepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery.timepicker.css" />
<script type="text/javascript" src="/lib2/bootstrap-datepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/lib2/bootstrap-datepicker.css" />

<script src="/js/jquery.ui.core.js"></script>
<script src="/js/jquery.ui.widget.js"></script>
<script src="/js/jquery.ui.datepicker.js"></script>

<!-- fancybox start here -->
<script type="text/javascript" src="/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<script type="text/javascript">
		$(document).ready(function() {	
					$("a#showuserpopups").fancybox({
					'width' : "100%",
					'height' : "100%",
					'speedIn'		:	600, 
					'speedOut'		:	200, 
					'overlayShow'	:	true
					});	
				});	
</script>

<script type="text/javascript">
$(function() {

                $( "#selected_date" ).datepicker({
                    showOn: "button",
                changeMonth: true,
                 changeYear: true,
                  dateFormat: 'yy-mm-dd',
        buttonImage: "<?php echo $this->siteurl; ?>calendar.gif"
                 });
    
                
      

		
	});
</script>

<!--start code for edit product-->

    @import "compass/css3";

.table-editable {
  position: relative;
  
  .glyphicon {
    font-size: 20px;
  }
}

.table-remove {
  color: #700;
  cursor: pointer;
  
  &:hover {
    color: #f00;
  }
}

.table-up, .table-down {
  color: #007;
  cursor: pointer;
  
  &:hover {
    color: #00f;
  }
}

.table-add {
  color: #070;
  cursor: pointer;
  position: absolute;
  top: 8px;
  right: 0;
  
  &:hover {
    color: #0b0;
  }
}
</style>

<div class="content">
        
        <div class="header">
            <h1 class="page-title">Edit FQB Details</h1>
        </div>
        
        <ul class="breadcrumb">
            <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
			<li class="active">Edit FQB Details<span class="divider">/</span></li>
           
        </ul>

	<div class="container-fluid" style="padding-top:162px;">
		
<div class="well"> 
        <!--Distance traveled section start here-->
        <form method="post" action="/fqb/edit-fqb">
              <input type="hidden" value="<?php echo $result['fqb_id'];?>" name="fqb_id"/>
            
           <div class="frmRow" style="float: left; width: 49%;">
            	<div class="frmColLeft">FQB No. :</div>
                   <div class="frmColRight">
                        <div class="acme_dtdp">
                            
                            <label><?php echo $result['fqb_no']; ?></label>
                        </div>
            	   </div>
            </div>
            <div class="frmRow" style="float: left; margin-left: 10px;">
            	<div class="frmColLeft">FQB Fill Date Time :</div>
                <div class="frmColRight">
                    <div class="acme_dtdp">
                        
                        <label><?php echo $result['fqb_filled_date_time'] ?></label>
                    </div>
            	</div>
            </div>
            <div class="clear"></div>
             
           <fieldset>
           <legend>Site Details</legend>
           <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft">Site ID :</div>
                <div class="frmColRight">
            	<div class="acme_dtdp">
                  <input style="height: 15px!important;"  type="text" value="<?php echo $result['site_id'] ?>" name="site_id" class="input-large">
<!--                  <a href="/fqb/all-sites" id="showuserpopups" class="iframe" >88</a>-->
                  <a href="fqb/all-sites" id="showuserpopups" class="btn btn-primary iframe" style="display: inline-block!important;
  padding: 0px 6px!important;
  margin-bottom: 4px!important;
  font-size: 15px!important;
  line-height: 23px!important;">Search</a>
                </div>
            	</div>
                <div class="clear"></div>
            </div>
            <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft">Address :</div>
                <div class="frmColRight">
            	<div class="acme_dtdp">
                    
                    <label><?php //echo $result['address'] ?></label>
                </div>
            	</div>
                <div class="clear"></div>
            </div>
                 <div class="frmRow" style="float: left; width: 51%;">
            	<div class="frmColLeft">Circle :</div>
                <div class="frmColRight">
            	<div class="acme_dtdp">
                    
                    <label><?php echo $result['circle'] ?></label>
                </div>
            	</div>
                <div class="clear"></div>
            </div>
            <div class="frmRow" style="float: left; width: 49%;">
            	<div class="frmColLeft">Cluster :</div>
                <div class="frmColRight">
            	<div class="acme_dtdp">
                    
                    <label><?php echo $result['cluster'] ?></label>
                </div>
            	</div>
                    <div class="clear"></div>
            </div>
           <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft">Name :</div>
                <div class="frmColRight">
            	<div class="acme_dtdp">
                  <label><?php echo $record['StaffName'] ?></label>
                </div>
            	</div>
                <div class="clear"></div>
            </div>
           <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft">Contact No. :</div>
                <div class="frmColRight">
            	<div class="acme_dtdp">
                    <label><?php echo $record['MobileNo'] ?></label>
                </div>
            	</div>
                <div class="clear"></div>
            </div>
            </fieldset>
             <fieldset>
                
            <legend>Photos</legend>
            <table style="width: 85%!important;
margin-bottom: 20px!important;
margin-left: 68px!important;">
                  <thead>
                    <tr>
                        
                        <th><img src="<?php echo $this->user;?><?php echo $result['site_photograph1'] ?>"/><br/><a href="/fqb/edit-fqb/fqbid/<?php echo $result['fqb_id'];?>/delete/<?php echo $result['fqb_id'];?>">Remove</a></th>
                      
                        <th><img src="<?php echo $this->user;?><?php echo $result['site_photograph2'] ?>"/><br/><a href="#">Remove</a></th>
                        
                        <th><img src="<?php echo $this->user;?><?php echo $result['site_photograph3'] ?>"/><br/><a href="#">Remove</a></th>
                       
                        <th><img src="<?php echo $this->user;?><?php echo $result['site_photograph4'] ?>"/><br/><a href="#">Remove</a></th>
                        
                        <th><img src="<?php echo $this->user;?><?php echo $result['site_photograph5'] ?>"/><br/><a href="#">Remove</a></th>
                     </tr>
                   </thead>
                  
              </table>
            </fieldset>
            
            <fieldset>
            <legend></legend>
            <div class="frmRow" style="float: left; width: 49%;">
            	<div class="frmColLeft">OME Remark :</div>
                <div class="frmColRight">
            	<div class="acme_dtdp">
                  
                    <p><?php echo $result['ome_remark'] ?></p>
                </div>
            	</div>
                
				 
            </div>
                <div class="frmRow" style="float: left; margin-left: 10px;">
            	<div class="frmColLeft">SME Remark :</div>
                <div class="frmColRight">
            	<div class="acme_dtdp">
                    <p><?php echo $result['sme_remarks'] ?></p>
                </div>
            	</div>
                
				 
            </div>
            </fieldset>
            <fieldset>
                
            <legend>Signature</legend>
             <div class="frmRow" style="float: left; width: 49%;">
                 <div class="frmColRight">
            	<div class="acme_dtdp">
                    
                 <img style="-webkit-box-shadow: 8px -4px 13px 2px rgba(63, 61, 59, 0.59);
-moz-box-shadow:    8px -4px 13px 2px rgba(63, 61, 59, 0.59);
box-shadow:         8px -4px 13px 2px rgba(63, 61, 59, 0.59); width: 200px; height: 200px; " src="<?php echo $this->signature;?><?php echo $result['ome_signature'] ?>"/><br/><a href="#"></a><label style="margin-left: 45px;">OME Signature</label>
                </div>
                 </div>
            	<div class="clear"></div>
            </div>
            <div class="frmRow" style="float: left; width: 49%;">
                 <div class="frmColRight">
            	<div class="acme_dtdp">
                    
                    <img style="-webkit-box-shadow: 8px -4px 13px 2px rgba(63, 61, 59, 0.59);
-moz-box-shadow:    8px -4px 13px 2px rgba(63, 61, 59, 0.59);
box-shadow:         8px -4px 13px 2px rgba(63, 61, 59, 0.59); width: 200px; height: 200px;" src="<?php echo $this->signature;?><?php echo $result['sme_signature'] ?>"/><br/><a href="#"></a><label style="margin-left: 45px;">SME Signature</label>
                </div>
                 </div>
            	<div class="clear"></div>
            </div>
           
            </fieldset>
            
            <fieldset>
                
            <legend>Product Details</legend>
             <div class="container-fluid">
   
        <div class="row-fluid" > 
            
            <a style="float:right; margin-top: 4px;" name="new-title" class="btn btn-primary">Add</a>
            <div class="block" id="acme_status">
            <div class="block-heading"> 
            
              <a href="javascript:void(0);" style="cursor:default;">Product Details</a>
              </div>
            <div id="widget2container" class="block-body collapse in">
            <table class="table">
                <thead>
                 <tr>
                        <th>S.No.</th>
                        <th>Product Name</th>
                        <th>Product Type</th>
                        <th>QTY</th>
                        <th>Rate</th>
                        <th>Action</th>
                     </tr>
                   </thead>
                   <tbody>
                       <?php
                       $fqb = new Application_Model_Fqb();
                       $addedProduct = $fqb->getProductForFqb($result['fqb_id']);
                       
                         $i=1; 
                    foreach($addedProduct as $key){
                        
                       ?>
                      <tr>
                           <td><?php echo $i; ?><input type="hidden" name="product_id[]" value="<?php echo $key['product_id'] ?>"></td>
                           <td><?php echo $key['product_name'];?></td>
                           <td><?php if($key['product_id']>0) { echo "Acme Product" ;} else { echo 'N-Acme Product';} ?></td>
                           <td><?php echo $key['qty']; ?></td>
                           <td><?php echo $key['rate']; ?></td>
                           <td><a href="#"><i class="icon-pencil"></i></a>   <a href="#"><i class="icon-remove"></i></a></td>
                      </tr>
                       <?php 
                       $i++;
                     }
                      
                       
                           ?>
                           
                           
                   </tbody>
             </table>
                <?php //if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); } ?>
            </div>
            </div>
        </div>
        
  </div>
            
            </fieldset>
            
            
        <div class="genrateBtn" style="margin-left:170px !important; padding-bottom:35px;">
              <button type="submit" class="btn btn-primary" value="Save">Update Fqb</button>
              <button type="submit" class="btn btn-primary" value="Cancle">Cancel</button>
                </div>
        </form>
        <!--Distance traveled section end here--> 
       </div>

</div>
</div>



