<?php 
$record = $this->record; 
$printcoursename = $this->printcoursename; 
 ?>



<link rel="stylesheet" href="/css1/datepicker/jquery.ui.all.css">
<script src="/js1/jquery-1.8.3.js"></script>
<script type="text/javascript" src="/js1/jquery.timepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/css1/jquery.timepicker.css" />
<script type="text/javascript" src="/lib2/bootstrap-datepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/lib2/bootstrap-datepicker.css" />
<link rel="stylesheet" type="text/css" href="/editor1/themes/flat/style.css" />
<script type="text/javascript" src="https://code.jquery.com/jquery-1.7.min.js"></script>
<script type="text/javascript" src="/editor1/cazary.min.js"></script>

<script type="text/javascript">
	(function($, window)
	{
		$(function($)
		{
			// that's it!
			$("textarea#id_cazary").cazary();

			// customized editor
			$("textarea#id_cazary_minimal").cazary({
				commands: "MINIMAL"
			});
			$("textarea#id_cazary_full").cazary({
				commands: "FULL"
			});
		});
	})(jQuery, window);
</script>
<script type="text/javascript" src="http://jqueryjs.googlecode.com/files/jquery-1.3.1.min.js" > </script> 
<script type="text/javascript">

    function PrintElem(elem){
		
        Popup($(elem).html());
    }

    function Popup(data) {
        var mywindow = window.open('', 'my div', 'height=1000,width=1000');
        mywindow.document.write('<html><head><title>OFFICERS TRAINING COLLEGE</title>');
        mywindow.document.write('<link rel="stylesheet" href="http://otc.logimetrix.me/css/materialize.css" type="text/css" />');
        mywindow.document.write("</head><body style='padding: 20px;margin: 0.5rem 0 1rem 0;border-radius: 2px;background-color: #fff;'>");
        mywindow.document.write(data);
        mywindow.document.write('</body></html>');

        mywindow.document.close(); // necessary for IE >= 10
        mywindow.focus(); // necessary for IE >= 10

        mywindow.print();
        mywindow.close();

        return true;
    }

</script>

  <section id="content">
    
         <!--breadcrumbs start-->
        <div id="breadcrumbs-wrapper" class=" grey lighten-3">
            <!-- Search for small screen -->
            <div class="header-search-wrapper grey hide-on-large-only">
                <i class="mdi-action-search active"></i>
                <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
            </div>
          <div class="container">
            <div class="row">
              <div class="col s12 m12 l12">
                
                <ol class="breadcrumb">
                 <li><a href="index-2.html">Dashboard</a>
                  </li>
                  <li><a href="#">Subject Detail</a>
                  </li>
                  <li class="active">Subject Detail</li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <!--breadcrumbs end-->
        


        <!--start container-->
        <div class="container">
         

     <div class="row" style="padding: 25px;" >
			   <div class="col s12 m4 l3">  <h5 class="header">Print Subject Detail</h5></div>
			   <div class="col s12 m8 l3">  <h5 class="header"></h5></div>
			   <div class="col s12 m12 l3">  <h5 class="header"></h5></div>
			 
			   <div class="col s12 m20 l3 right-mragin" style="margin-top:10px; mrgin-right:10px; height:50px; text-align: right;  "> 
				    <a class="btn waves-effect waves-light blue" onclick="PrintElem('#mydiv')" href="javascript:void(0)">print</a></div>
                 <div class="col s12">
                
        
                   <div class="row" style="padding:60px;"> 
				   
	<div class="card-panel" id="mydiv">
		 <table>
               <tr>
				   <td style="text-align:center;"><strong><ins>BLOCK SYLLABUS</ins></strong><br/><strong><ins><?php   echo $printcoursename['course_name'];   ?>&nbsp;COURSE</ins></strong><br/><strong id="abc"></strong>&nbsp;&nbsp;<strong></strong></td>
			  </tr></table>
              <table><tr></tr>
			   <tr><td style="text-align:left;">1.&nbsp;&nbsp;&nbsp;Duration</td><td>:</td><td>Eight Weeks</td></tr>
			   <tr><td style="text-align:left;">2.&nbsp;&nbsp;&nbsp;Total No Of Working Days(6*8) </td><td>:</td><td>48</td></tr>
			   <tr><td style="text-align:left;">3.&nbsp;&nbsp;&nbsp;Trg Period </td><td></td><td></td></tr>
			   <tr><td style="text-align:left;">a.&nbsp;&nbsp;&nbsp;No Of Period Per Day</td><td>:</td><td>07</td></tr>
			   <tr><td style="text-align:left;">b.&nbsp;&nbsp;&nbsp;Total No Of Period(7*6*8)</td><td>:</td><td>336</td></tr>
			   <tr> <td style="text-align:left;">4.&nbsp;&nbsp;&nbsp;Allotment Of Periods</td><td></td><td></td></tr>			  
       </table>   
         <div class="well" style="height:auto;">
               <table   style="padding:30px; border:1px solid;">
                  <thead style=" border:1px solid;">
                    <tr style=" border:1px solid;">
                        <th data-field="id" style=" border:1px solid;">S.No.</th>
						  <th data-field="name" style=" border:1px solid;">Subject Code</th> 
                          <th data-field="name" style=" border:1px solid;">Subject Name</th>                    
                        <th data-field="name">No of Periods</th>
             		
                    </tr>
                  </thead>
                    <tbody style=" border:1px solid;">
					 	 <?php
					
                           $i=1;
	                       foreach($record  as $key=>$valu){
							   $user = new Application_Model_Usersotc();
							   $clcdsumBysubjectId  = $user->clcdsumBysubjectId($valu['id']);
		                       $demoSumBysubjectId  = $user->demoSumBysubjectId($valu['id']);
		                       $getoeSumBysubjectId  = $user->getoeSumBysubjectId($valu['id']);
		                       $getvisitSumBysubjectId  = $user->getvisitSumBysubjectId($valu['id']);
		                       $tot_period = $clcdsumBysubjectId['sum_clcd'] + $demoSumBysubjectId['sum_demo'] + $getoeSumBysubjectId['sum_oe'] + $getvisitSumBysubjectId['sum_visit'];
                      ?>					
						<tr>
							<td style=" border:1px solid;"><?php echo $i;?></td>
							<td style=" border:1px solid;"><?php echo $valu['subject_code'];?></td>
							<td style=" border:1px solid;"><?php echo $valu['subject_name'];?></td>
							<td style=" border:1px solid;"><?php echo $tot_period ;?></td>
						</tr>
						  
						
						<?php $i++; } ?> 
                  </tbody>
                </table>
        </br>
		<?php         
		
		   $i=1;
		  
	       foreach($record  as $key=>$valu){
			      
		?>
		 </br>
		<table>
               <tr>
				   <td style="text-align:center;"><strong><ins><?php   echo $valu['subject_name'];   ?></ins></strong><br/><strong id="abc"></strong>&nbsp;&nbsp;<strong></strong></td>
			  </tr>
              <tr></tr>			   
       </table>
        <table   style="padding:30px; border:1px solid;">
                  <thead style=" border:1px solid;">
				
                    <tr style=" border:1px solid;">
                        <th data-field="id" style=" border:1px solid;">S.No.</th>
						<th data-field="name" style=" border:1px solid;">Subject Code</th> 
                        <th data-field="name" style=" border:1px solid;">Subject Name</th>                                     
                        <th data-field="name" style=" border:1px solid;">CL/CD</th>
						<th data-field="name" style=" border:1px solid;">Demo</th>
						<th data-field="name" style=" border:1px solid;">OE</th>
						<th data-field="name" style=" border:1px solid;">Visit</th>
						<th data-field="name" style=" border:1px solid;">Total</th>
             		
                    </tr>
                  </thead>
                    <tbody style=" border:1px solid;">
					
					 	 <?php
					
                           $j=1;
		                   $user = new Application_Model_Usersotc();
				           $topicsListById  = $user->topicsListById($valu['id']);
						   if($topicsListById ){
	                       foreach($topicsListById as $key=>$valu1){
							   
                      ?>					
							<tr>
								<td style=" border:1px solid;"><?php echo $i;?></td>
								<td style=" border:1px solid;"><?php echo $valu1['subject_code'];?></td>
								<td style=" border:1px solid;"><?php echo $valu1['topic_name'];?></td>
								<td style=" border:1px solid;"><?php echo $valu1['clcd'];?></td>
								<td style=" border:1px solid;"><?php echo $valu1['demo'];?></td>
								<td style=" border:1px solid;"><?php echo $valu1['oe'];?></td>
								<td style=" border:1px solid;"><?php echo $valu1['visit'];?></td>
								<td style=" border:1px solid;"><?php echo$valu1['clcd'] + $valu1['demo'] + $valu1['oe'] + $valu1['visit'];?></td>
							</tr>
						  
						   <?php  $j++; }}  else{?>
						   <tr><td colspan="8">Result not found.</td></tr>
						   <?php  } ?>
					
                  </tbody>
                </table>
	   
	   
		   <?php  $i++; }  ?>
		      
		   
		   
  </div>
  </div>
   </div>
     </div> 
   
     </div>
      </div>
       </div>
  </section>
