<?php
	$record = $this->record; 
	$totalrec = $this->totalrec;
//	$get = $this->get;//
	$params = $this->params;

	$userList = $this->getAllUser;
        
?>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script>
function deleteTask(batchId){
		var confirmText = "Are you sure you want to delete this Institute now ?";
          
		if(confirm(confirmText)) {
				var parameters = 'batchId='+ batchId;
					//alert(parameters);
				    $.ajax({
						url: '/batch/delete-task',
						type: 'POST',
						data: parameters,
						success: function(msg){						 
						 $("#user_del_message").fadeIn("fast");
						 $("#user_del_message").fadeOut(6000);
						 //sleep(4);
						 window.location.reload();
						}						
					});
		}
		 return false;	
}


function validateUser(){ 
             
			if(document.getElementById("update").value !=""){
		         alert("Task detail update successfully.");
		         document.getElementById("update").focus();
		         return false;
		    }
			
	        return true;
	}

</script>

</script>
  <section id="content">
    
         <!--breadcrumbs start-->
        <div id="breadcrumbs-wrapper" class=" grey lighten-3">
            <!-- Search for small screen -->
           
          <div class="container">
            <div class="row" >
              <div class="col s12 m12 l12">
                
                <ol class="breadcrumb">
                  <li><a href="#">Subject Detail</a>
				  
                  </li>
                  <li class="active">Index</li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <!--breadcrumbs end-->
        <!--start container-->
        <div class="container">         
          <!--Form Advance-->
		  
             <div class="row">
               <!--   <form class="col s12" method="post" name="retailerregistration" action="/task/index" onsubmit="return validateUser();">                    
                    <div class="row" style="margin-top: 18px">
                      <div class="input-field col s3">
                        <select name="employee">
						    <option value="">--Select Employee--</option>
							<?php 
							  if($userList>0){
								  foreach($userList as $value){ ?>
									<option value="<?php echo $value['LoginID'];?>"<?php if ($params['employee'] == $value['LoginID']) echo ' selected="selected"'; ?>><?php echo $value['StaffName'];?></option>
							<?php }
							  }else{
							?>
								  <option value="">No User Available!!!</option>
							<?php } ?>
                        </select>
                        <label for="first_name" style=" margin-top: -7px;">Select Employee</label>
                      </div>                        
                      <div class="input-field col s3">
                        <input name="date1" type="date" id="d" placeholder="Date From" value = "<?php echo $params['date1'];  ?>"> 
                        <label for="first_name" style=" margin-top: -27px;">Choose Date From</label>						
                      </div>
					  <div class="input-field col s3">
                        <input name="date2" type="date" id="d1" value = "<?php echo $params['date2'];  ?>">
                       <label for="first_name" style=" margin-top: -27px;">Choose Date To</label>						
                      </div>
					  <div class="input-field col s2" style=" margin-top: 4px;">
                        <button class="btn cyan waves-effect waves-light right" type="submit" name="action">Search<i class="mdi-content-send right"></i></button>                       
                      </div>               
                    </div>
                  </form>-->        
            <div class="row" style="padding: 25px;">
			   <div class="col s12 m4 l3">  <h5 class="header">Subject Detail</h5></div>
			   <div class="col s12 m8 l3">  <h5 class="header"></h5></div>
			   <div class="col s12 m12 l3">  <h5 class="header"></h5></div>
			 
			  
                 <div class="col s12">
                  <table class="striped">
                  <thead>
                    <tr>
                        <th data-field="id">S.No.</th>
					
                          <th data-field="name">Subject Code</th> 						  
                          <th data-field="name">Subject Name</th>                    
                          <th data-field="name">No of Periods</th>
						
             		
						<th data-field="total">Action</th>
                    </tr>
                  </thead>
                    <tbody>
					  <?php
                           $i=1;
	                       foreach($record as $key=>$val){
							   $user = new Application_Model_Usersotc();
							   $getgroupListBygrpId  = $user->getgroupListBygrpId($val['grp_id']);
							   $gettopicListBysubjectId  = $user->gettopicListBysubjectId($val['id']);
							   
	                           $clcdsumBysubjectId  = $user->clcdsumBysubjectId($val['id']);
							   $demoSumBysubjectId  = $user->demoSumBysubjectId($val['id']);
							   $getoeSumBysubjectId  = $user->getoeSumBysubjectId($val['id']);
							   $getvisitSumBysubjectId  = $user->getvisitSumBysubjectId($val['id']);
					          
							  $tot_period = $clcdsumBysubjectId['sum_clcd'] + $demoSumBysubjectId['sum_demo'] + $getoeSumBysubjectId['sum_oe'] + $getvisitSumBysubjectId['sum_visit']; 
							 
                      ?>					
									<tr>
										  <td><?php echo $i;?></td>
									
										  <td><?php echo $val['subject_code'];?></td>
										  <td><?php echo $val['subject_name'];?></td>
										  <td><?php echo $tot_period;?></td>
										
										  <td>
										      <?php if(!$gettopicListBysubjectId['number']){  ?>
												 <a href="/coursedetail/add-topic/subjectId/<?php echo $val['id'];?>" title="Add Subject" > <i class="mdi-content-add-box"></i></a> |
											  <?php  } else{ ?>
											  
											     <a href="/coursedetail/edit-topic/subjectId/<?php echo $val['id'];?>" title="Edit Subject" > <i class="mdi-editor-border-color"></i></a> |
											  <?php } ?>
											     <a href="/coursedetail/topicsdetail/subjectId/<?php echo $val['id'];?>" title="View" > <i class="mdi-action-view-module"></i></a>
												 
												  
												 
									</tr>
					<?php  $i++;}  ?>  			
 
                  </tbody>
                </table>
                </div>
              </div>
            </div>
                    
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
      </div>
  </section>
