  <?php
  $userList = $this->getAllUser;
  $userList = $this->getAllInstituteDetail;
  $rnk = $this->rnk;
  ?>


<script>
    $(function() {
		$( "#d" ).datepicker({
			showOn: "button",
			buttonImage: "http://runapp.me/images/calendar.gif",
			dateFormat: 'yy-mm-dd',
			buttonImageOnly: true,
			buttonText:'Date Of Birth',
                        changeMonth: true,
                        changeYear: true
		});
			
               
              
    });
</script>

  <section id="content">
    
         <!--breadcrumbs start-->
        <div id="breadcrumbs-wrapper" class=" grey lighten-3">
            <!-- Search for small screen -->
            <div class="header-search-wrapper grey hide-on-large-only">
                <i class="mdi-action-search active"></i>
                <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
            </div>
          <div class="container">
            <div class="row">
              <div class="col s12 m12 l12">
                
                <ol class="breadcrumb">
                 <li><a href="#">Home</a>
                  </li>
                  <li><a href="#">Course Detail</a>
                  </li>
                  <li class="active">Add Course Detail</li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <!--breadcrumbs end-->
        


        <!--start container-->
        <div class="container">
         

         
        

          <!--Form Advance-->          
          <div class="row">
            <div class="col s12 m12 l12">
              <div class="card-panel">
			        <?php if($this->successMessage) { ?>
                                <div class="alert alert-success">
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><?php echo $this->successMessage;?>
                                </div>  
				    <?php } ?> 
                <h4 class="header2">Add Course</h4>
                <div class="row">
                  <form class="col s12" method="post" action="/course/add-course" enctype="multipart/form-data">
                    
                    <div class="row">

                      


                     <div class="input-field col s6">
                          <input placeholder="Enter Course Name " id="tname" type="text" name='course_name' required class="validate">
                          <label for="institute_name">Course Name</label>
                        </div> 
                        
                        
                        <div class="input-field col s6">
                          <input placeholder="Enter No of weeks " id="tname" type="text" name='duration' required class="validate">
                          <label for="institute_name">Duration</label>
                        </div> 
                      
                      
                    </div>
                    
                                 

					  <div class="row">
                     
                      
                  
                      <div class="row">
                        <div class="input-field col s12">
                          
                          <button class="btn cyan waves-effect waves-light right" type="submit" name="action">Add Course Detail
                            <i class="mdi-content-send right"></i>

                          </button>
</div>
                        </div>
                    
                    </div>

		
                  </form>
                </div>
              </div>
            </div>
          </div>
      </div>
  </section>