<?php
$auth = Zend_Auth::getInstance();
$authStorage = $auth->getStorage();
$params = $this->params;
$Record = $this->Record;



?>




<link rel="stylesheet" href="/css/datepicker/jquery.ui.all.css">

<script src="/js/jquery-1.8.3.js"></script>

<script type="text/javascript" src="/js/jquery.timepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery.timepicker.css" />
<script type="text/javascript" src="/lib2/bootstrap-datepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/lib2/bootstrap-datepicker.css" />

<script src="/js/jquery.ui.core.js"></script>
<script src="/js/jquery.ui.widget.js"></script>
<script src="/js/jquery.ui.datepicker.js"></script>

<script>



function validatechemicaltype()
{  
        if(document.getElementById("chemical_type").value=="")
	{
	 alert("Please select chemical type.");
	 document.getElementById("chemical_type").focus();
	 return false;
	}
	
	
         
  return true;
}
      



            
</script>



<div class="content">
        
        <div class="header">
            <h1 class="page-title">Edit Chemical Type </h1>
        </div>
        
        <ul class="breadcrumb">
            <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
			<li >All Masters<span class="divider">/</span></li>
                        <li class="active">Edit Chemical Type<span class="divider">/</span></li>
           
        </ul>
     

		
		<?php if($this->errorMessage) { ?>
		<div class="alert alert-error">
			<button data-dismiss="alert" class="close" type="button">×</button>
			<?php echo $this->errorMessage;?>
		</div>
	   <?php } ?>
	<div class="well" style="padding:0 10px; width:auto;   margin-left: 10px;
  margin-right: 10px;
  -webkit-border-radius: 10px!important;">
             
      
       <form id="myform" method="post" name="addUnitDetails" action="/chemical/edit-chemical"  onsubmit="return validatechemicaltype();"  >
            <input type="hidden" value="<?php echo $params['code'];?>" name="id" id="id"> 
            <fieldset>
            <legend>Chemical Type Details</legend>
        
            
            
             <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">Chemical Type :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;"> 
                     <input type="text" value="<?php echo $Record['chemical_type'];?>" name="chemical_type" id="chemical_type"> 
              
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            
            
            
            </fieldset>
            
            
            
           
          
              <div class="genrateBtn" style="margin-left:170px !important; margin-top: 25px; padding-bottom:35px; ">
              <button type="button" class="btn btn-primary" value="Cancel">Cancel</button>
              <button type="submit" class="btn btn-primary" value="Save">Save Changes</button>
              </div>
        </form>
</div>
    </div>



