<?php 
$get = $this->get;
$params = $this->params;
$record = $this->paginator; 
$totalrec = $this->totalrec;

// Start reset url code
$auth = Zend_Auth::getInstance();
$authStorage = $auth->getStorage();
$role = $authStorage->read()->Role;


?>

<script type="text/javascript">
function goback() {
    history.go(-1);
}
</script>

<!-- fancybox start here -->
<script type="text/javascript" src="/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<script type="text/javascript">
	$(document).ready(function() {	
				$("a#view-details").fancybox({
				'transitionIn'	:	'elastic',
				'transitionOut'	:	'elastic',
				'width' : 1000,
				'height' : 800,
				'speedIn'		:	600, 
				'speedOut'		:	200, 
				'overlayShow'	:	true
				});	
			});
$(document).ready(function() {	
				$("a#view-sowing").fancybox({
				'transitionIn'	:	'elastic',
				'transitionOut'	:	'elastic',
				'width' : 1000,
				'height' : 800,
				'speedIn'		:	600, 
				'speedOut'		:	200, 
				'overlayShow'	:	true
				});	
			});	
	
function deleteChemical(Id)
{
		var confirmText = "Are you sure you want to delete this Seed Order now ?";
		 if(confirm(confirmText)) {
		 
				
				var parameters = 'chemical_Id='+Id;
					// alert(parameters);
				    $.ajax({
						url: '/chemicalorders/delete-chemical',
						type: 'POST',
						data: parameters,
						success: function(msg)
						{
							//alert(msg);
                                                  
                          window.location.reload();
                                                  
                                               
						  $("#user_del_message").fadeIn("fast");
						  $("#user_del_message").fadeOut(6000);
                                                 
                                                   sleep(4); 
						}
                                                
					});
		 }
		 return false;	
}	
			
</script> 





<!-- Search ajax end here -->

<div class="content">
        
        <div class="header">
            <h1 class="page-title">Chemical Order Details </h1>
        </div>
        <div class="breadcrumb">
        <div style="position:relative;">
        <ul class="imop">
          <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
			<li>Chemical Orders<span class="divider">/</span></li>
                        <li class="active">Chemical Order Details<span class="divider">/</span></li>
        </ul>
       
        </div>
        <a href="javascript:void(0);" style="position:absolute; right:10px; top:5px; border: 1px solid; background-color: #4d5b76; color: #fff; padding:1px 6px; font-size:12px; font-weight:bold; display:block;" id="showuserlocation" class="iframe" onClick="goback();">Back</a>
        </div>
<script>
$(document).ready(function() {
    $('.breadcrumb').css({'width':(($(window).width())-270)+'px'});
	$(window).resize(function(){
       $('.breadcrumb').css({'width':(($(window).width())-270)+'px'}); 
    });
});
</script>
<style>
.tableheading{
	background-color: #e2e2e2;
	color: #000;
	font-weight: bold;
	text-align: center;
	padding-bottom: 5px;
	border-bottom: 1px solid #cfcccc;
}
.txt_center{
	text-align:center !important;
}
.imop{
margin:0px !important;
}
</style>
        <div class="container-fluid" style="padding-top:162px;">

<!--- user filtor by role end --->

 <div class="row-fluid" style="margin-top:10px;">
                    


            <?php if($this->successMessage) { ?>
		<div class="alert alert-info">
				<button data-dismiss="alert" class="close" type="button">×</button>
				<?php echo $this->successMessage;?>
		</div>	
		<?php } ?>
		
		<?php if($this->errorMessage) { ?>
		<div class="alert alert-error">
			<button data-dismiss="alert" class="close" type="button">×</button>
			<?php echo $this->errorMessage;?>
		</div>
	   <?php } ?>
			
<div class="well" style="overflow:scroll;" >
 <a href="/chemicalorders/index/seed/Generate" class="btn btn-primary" type="submit" style="margin-bottom: 5px;">Export In Excel</a>
     <table class="table tablesorter">
      <thead>

	  <tr><td colspan="13" class="tableheading">Chemical Orders</td></tr>
        <tr>
<th>S. No.</th>
<th>Farmer Code</th>
<th>Farmer Name</th>
<th>Chemical Name</th>
<th>Chemical Type</th>
<th>Qty</th>
<th>Rate</th>
<th>Booking Date</th>
<th>Date of Delivery</th>
<th>Details</th>
 <th>Action</th>
 </tr>
      </thead>
      <tbody>
       <?php
	   	
	if($totalrec)
	{
            
          $i=1;
	  foreach($record as $key=>$val)
	  {
	?>
        <tr>
          <td><?php echo $i; ?></td>
          <td><?php echo $val['FarmerCode'];?></td>
          <td><?php echo $val['FarmerName'];?></td>
          <td><?php echo $val['chemical_name'];?></td>
          <td><?php echo $val['chemical_type_id'];?></td>
          <td><?php echo $val['Quantity'].' '.$val['rate_per_unit'];?></td>
          <td><?php echo $val['date_of_order'];?></td>
          <td><?php echo $val['date_delivery'];?></td> 
          <td><a href="/chemicalorders/order-details/data/<?php echo md5($val['orderId']);?>" class="iframe" id="view-details" title="View Details">view</a></td>
            <td><a href="javascript:void(0);" onclick="deleteChemical('<?php echo $val['orderId'];?>')" >Delete</a></td> 
<!--          <td><a href="/chemicalinfo/edit-chemical-detail/data/<?php echo md5($val['ChemicalID']);?>"><i class="icon-pencil"></i></a>
          </td>-->
        </tr>

           <?php $i++; } } else { ?>  
	   <tr><td colspan="8">Result not found.</td></tr>
	   <?php } ?>

      </tbody>
    </table>
</div>
<!--Pagingnation Start-->
<?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); } ?>
</div>
</div>
</div>
    
   
