<table border="1" style="background-color:#FFFFFF;border-collapse:collapse;border:1px solid #000000;color:#000000;width:100%" cellpadding="3" cellspacing="3">
	<tr>
		<th colspan="3"  style="float:center">Table Cell</th>
		
	</tr>
	<tr>
			<th colspan="3"  style="float:center">Table Cell</th>
                  
		
	</tr>
	<tr>
		<th>Table Cell</th>
		<th>Table Cell</th>
		<th>Table Cell</th>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
</table>
