  <?php
     echo $this->headScript()->prependFile('/js/print.js');
    ?>

<a href="javascript: void(0);" onclick="printpage('print');"><button class="btn btn-primary" style="width:90px; font-family:verdana;font-size:13px;" value="Submit" type="submit" name="submit" id="submit">Print</button></a>

<div id="print">
<h3 align="center">Final Evalution MOBC - 206 WEF 11 AUG 15 to 12 OCT 15</h3>
<table border="2" style="background-color:#CCC;border-collapse:collapse;border:2px solid #FFCC00;color:#000000;width:100%; font-size:13px;">
	<tr>
		
		<th>PT</th>
		<th>PPT</th>
		<th>BPET</th>
		<th>DRILL</th>
		<th>BR</th>
		<th>MR</th>
		<th>RGCL</th>
		<th>CS & OLQ</th>
		<th>TOTAL GP-1</th>
	    <th>% GP-I</th>
		<th>ML</th>
		<th>SD</th>
		<th>UAHA</th>
		<th>RMO</th>
		<th>SANRD</th>
		<th>TOTAL GPII</th>
		<th>% GP-II</th>
	    <th>OE(A&S)& </th>
		<th>OE(Med)&C </th>
		<th>EXUPCHAR</th>
		<th>WG I</th>
	    <th>WG II</th>
		<th>EXAKRMAR</th>
		<th>TOTAL GP-III</th>
		<th>% GP-III</th>
		<th>GPs total</th>
		<th>%</th>
		<th>GRADING</th>
		<th>Posns</th>
	<th>P.No</th>
	</tr>
	<tr>
		<td>20</td>
		<td>20</td>
		<td>20</td>
		<td>50</td>
		<td>10</td>
		<td>20</td>
		<td>30</td>
		<td>30.00</td>
		<td>200</td>
		<td>100</td>
		<td>25</td>
		<td>25</td>
		<td>50</td>
		<td>75</td>
		<td>25</td>
		<td>200</td>
		<td>100</td>
		<td>50</td>
		<td>50</td>
		<td>25</td>
		<td>25</td>
		<td>25</td>
		<td>25</td>
		<td>200</td>
		<td>100</td>
		<td>600.00</td>
		<td>100.00</td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td>16.00</td>
		<td>9.00</td>
		<td>2.50</td>
		<td>34.00</td>
		<td>7.00</td>
		<td>15.50</td>
		<td>22.18</td>
		<td>20.00</td>
		<td>200</td>
		<td>100</td>
		<td>25</td>
		<td>25</td>
		<td>50</td>
		<td>75</td>
		<td>25</td>
		<td>200</td>
		<td>100</td>
		<td>50</td>
		<td>50</td>
		<td>25</td>
		<td>25</td>
		<td>25</td>
		<td>25</td>
		<td>200</td>
		<td>100</td>
		<td>600.00</td>
		<td>100</td>
		<td>C</td>
		<td>74</td>
		<td>1</td>
	</tr>
		<tr>
		<td>15.00</td>
		<td>11.00</td>
		<td>9.00</td>
		<td>34.00</td>
		<td>7.50</td>
		<td>13.50</td>
		<td>17.96</td>
		<td>20.50</td>
		<td>128.46</td>
		<td>64.23</td>
		<td>8.88</td>
		<td>13.88</td>
		<td>22.25</td>
		<td>51.25</td>
		<td>15.50</td>
		<td>111.75</td>
		<td>55.88</td>
		<td>24.75</td>
		<td>27.50</td>
		<td>16.00</td>
		<td>14.00</td>
		<td>14.00</td>
		<td>15.00</td>
		<td>111.25</td>
		<td>55.63</td>
		<td>351.46</td>
		<td>58.58</td>
		<td>C</td>
		<td>74</td>
		<td>2</td>
	</tr>
	<tr>
		<td>14.00</td>
		<td>15.00</td>
		<td>17.00</td>
		<td>38.00</td>
		<td>7.00</td>
		<td>15.50</td>
		<td>18.39</td>
		<td>19.00</td>
		<td>143.89</td>
		<td>71.95</td>
		<td>12.38</td>
		<td>13.00</td>
		<td>22.25</td>
		<td>44.75</td>
		<td>16.00</td>
		<td>108.38</td>
		<td>54.19</td>
		<td>27.75</td>
		<td>35.50</td>
		<td>16.50</td>
		<td>14.10</td>
		<td>17.00</td>
		<td>16.00</td>
		<td>126.85</td>
		<td>63.43</td>
		<td>379.12</td>
		<td>63.19</td>
		<td>B</td>
		<td>38</td>
		<td>3</td>
	</tr>
</table>
</div>
