<?php 
$record = $this->paginator; 
$totalrec = $this->totalrec;
$get = $this->get;
$params = $this->params;

// Start reset url code
$auth = Zend_Auth::getInstance();
$authStorage = $auth->getStorage();
$role = $authStorage->read()->Role;


?>

<script type="text/javascript">
function goback() {
    history.go(-1);
}
</script>




<!-- Search ajax end here -->

<div class="content">
        
        <div class="header">
            <h1 class="page-title">Manage Village List </h1>
        </div>
        <div class="breadcrumb">
        <div style="position:relative;">
        <ul class="imop">
          <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
			<li >All Masters<span class="divider">/</span></li>
                        <li class="active">Manage Village List<span class="divider">/</span></li>
        </ul>
       
        </div>
        <a href="javascript:void(0);" style="position:absolute; right:10px; top:5px; border: 1px solid; background-color: #4d5b76; color: #fff; padding:1px 6px; font-size:12px; font-weight:bold; display:block;" id="showuserlocation" class="iframe" onClick="goback();">Back</a>
        </div>
<script>
$(document).ready(function() {
    $('.breadcrumb').css({'width':(($(window).width())-270)+'px'});
	$(window).resize(function(){
       $('.breadcrumb').css({'width':(($(window).width())-270)+'px'}); 
    });
});
</script>
<style>
.tableheading{
	background-color: #e2e2e2;
	color: #000;
	font-weight: bold;
	text-align: center;
	padding-bottom: 5px;
	border-bottom: 1px solid #cfcccc;
}
.txt_center{
	text-align:center !important;
}
.imop{
margin:0px !important;
}
</style>
        <div class="container-fluid" style="padding-top:162px;">

<!--- user filtor by role end --->

 <div class="row-fluid" style="margin-top:10px;">
                    
<div class="search-well">
	<div class="form-inline">
	<form class="form-inline" style="width:870px; float: left;" method="get" action="" style="margin-bottom:10px;">
		<input type="text" name="search" id="search" placeholder="Search Here..." value="<?php echo $get['search'];?>" class="input-large">
		<input type="hidden" name="staffCode" id="staffCode" value="<?php echo $this->supervisorStaffCode;?>">
		<button type="submit" class="btn" id="searchbtn" style="position:relative; text-align:center; padding-left:22px;"><span class="search"></span> Go</button>
		<button type="button" class="btn" > Reset</button>
		</form>
            <a href="/village/add-village" class="btn btn-primary">Add New Village</a>
	</div>
</div>

  <?php if($params['type']=='success') { ?>
		<div class="alert alert-info">
				<button data-dismiss="alert" class="close" type="button">×</button>
				Village has been Updated Successfully.
		</div>	
		<?php } ?>
            <?php if($this->successMessage) { ?>
		<div class="alert alert-info">
				<button data-dismiss="alert" class="close" type="button">×</button>
				<?php echo $this->successMessage;?>
		</div>	
		<?php } ?>
		
		<?php if($this->errorMessage) { ?>
		<div class="alert alert-error">
			<button data-dismiss="alert" class="close" type="button">×</button>
			<?php echo $this->errorMessage;?>
		</div>
	   <?php } ?>
			
<div class="well" style="overflow:scroll; height:auto;">
    <table class="table tablesorter">
      <thead>

	  <tr><td colspan="13" class="tableheading">Manage Village List</td></tr>
        <tr>

<th>Circle</th>
<th>Circle Code</th>
<th>State</th>
<th>District </th>
<th>Tehsil </th>
<th>Region </th>
<th>Village </th>
<th>Pin Code </th>
<th>Action</th>
 </tr>
      </thead>
      <tbody>
       <?php
	   	
	if($totalrec)
	{
          $i=1;
	  foreach($record as $key=>$val)
	  {
	?>
        <tr>
          <td><?php echo $val['Circle'];?></td>
          <td><?php echo $val['CircleCode'];?></td>
          <td><?php echo $val['state'];?></td>
           <td><?php echo $val['district_name'];?></td>
            <td><?php echo $val['tehsil_name'];?></td>
             <td><?php echo $val['RegionName'];?></td>
              <td><?php echo $val['village_name'];?></td>
              <td><?php echo $val['pincode'];?></td>
          <td><a href="/village/edit-village/villageCode/<?php echo md5($val['id']);?>"><i class="icon-pencil"></i></a> 
<!--              <a><i class="icon-remove"></i></a>-->
          </td>
        </tr>

           <?php } } else { ?>  
	   <tr><td colspan="8">Result not found.</td></tr>
	   <?php } ?>

      </tbody>
    </table>
</div>

<!--Pagingnation Start-->
<?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); } ?>
	</div>
</div>
</div>
    
   
