<?php 
$get = $this->get;
$params = $this->params;

// Start reset url code
$auth = Zend_Auth::getInstance();
$authStorage = $auth->getStorage();
$role = $authStorage->read()->Role;


?>

<script type="text/javascript">
function goback() {
    history.go(-1);
}

function deleteAppsetting(Id,mode)
{
		var confirmText = "Are you sure you want to delete this?";
		 if(confirm(confirmText)) {
		 
				var parameters = 'appId='+Id+'&mode='+mode;
					 //alert(parameters);
				    $.ajax({
						url: '/appsetting/deleteapp',
						type: 'POST',
						data: parameters,
						success: function(msg)
						{
							//alert(msg);
                                                  
                          window.location.reload();
                                                  
                                               
						  $("#user_del_message").fadeIn("fast");
						  $("#user_del_message").fadeOut(6000);
                                                 
                           sleep(4); 
						}
                                                
					});
		 }
		 return false;	
}
</script>




<!-- Search ajax end here -->

<div class="content">
        
        <div class="header">
            <h1 class="page-title">Farmer Land Masters </h1>
        </div>
        <div class="breadcrumb">
        <div style="position:relative;">
        <ul class="imop">
          <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
			<li >Farmer Master<span class="divider">/</span></li>
                        <li class="active">Farmer Land Masters<span class="divider">/</span></li>
        </ul>
       
        </div>
        <a href="javascript:void(0);" style="position:absolute; right:10px; top:5px; border: 1px solid; background-color: #4d5b76; color: #fff; padding:1px 6px; font-size:12px; font-weight:bold; display:block;" id="showuserlocation" class="iframe" onClick="goback();">Back</a>
        </div>
<script>
$(document).ready(function() {
    $('.breadcrumb').css({'width':(($(window).width())-270)+'px'});
	$(window).resize(function(){
       $('.breadcrumb').css({'width':(($(window).width())-270)+'px'}); 
    });
});
</script>
<style>
.tableheading{
	background-color: #e2e2e2;
	color: #000;
	font-weight: bold;
	text-align: center;
	padding-bottom: 5px;
	border-bottom: 1px solid #cfcccc;
}
.txt_center{
	text-align:center !important;
}
.imop{
margin:0px !important;
}
</style>
        <div class="container-fluid" style="padding-top:162px;">

<!--- user filtor by role end --->

 <div class="row-fluid" style="margin-top:10px;">
                    


  <?php if($params['type']=='success') { ?>
		<div class="alert alert-info">
				<button data-dismiss="alert" class="close" type="button">×</button>
				Farmer Type has been Updated Successfully.
		</div>	
		<?php } ?>
            <?php if($this->successMessage) { ?>
		<div class="alert alert-info">
				<button data-dismiss="alert" class="close" type="button">×</button>
				<?php echo $this->successMessage;?>
		</div>	
		<?php } ?>
		
		<?php if($this->errorMessage) { ?>
		<div class="alert alert-error">
			<button data-dismiss="alert" class="close" type="button">×</button>
			<?php echo $this->errorMessage;?>
		</div>
	   <?php } ?>
			
<div class="well" style="overflow:scroll; height:220px; width: 46% !important; float: left! important; margin: 4px;" >
    <a href="/appsetting/add-key/key/lastcrop/" class="btn btn-primary" style="float:right; margin-bottom: 4px;">Add Last Crop</a>
    <table class="table tablesorter">
      <thead>

	  <tr><td colspan="13" class="tableheading">Manage Last Crop</td></tr>
        <tr>

<th>Last Crop</th>

<th>Action</th>
 </tr>
      </thead>
      <tbody>
       <?php
	   	
	if($this->LastCrops)
	{
          $i=1;
	  foreach($this->LastCrops as $val)
	  {
	?>
        <tr>
          <td><?php echo $val['lastcrop'];?></td>
       
          <td><a href="/appsetting/edit-key/key/lastcrop/code/<?php echo md5($val['id']);?>"><i class="icon-pencil"></i></a> 
|  <a href="javascript:void(0);" onclick="deleteAppsetting('<?php echo md5($val['id']);?>','lastcrop')" ><i class="icon-remove"></i></a>
          </td>
        </tr>

           <?php } } else { ?>  
	   <tr><td colspan="8">Result not found.</td></tr>
	   <?php } ?>

      </tbody>
    </table>
</div>
<div class="well" style="overflow:scroll; height:220px; width: 46% !important; float: left! important; margin: 4px;" >
    <a href="/appsetting/add-key/key/lastrabi" class="btn btn-primary" style="float:right; margin-bottom: 4px;">Add Last Rabi Crop</a>
    <table class="table tablesorter">
      <thead>

	  <tr><td colspan="13" class="tableheading">Manage Rabi Crop</td></tr>
        <tr>

<th>Rabi Crop</th>

<th>Action</th>
 </tr>
      </thead>
      <tbody>
       <?php
	   	
	if($this->RabiCrop)
	{
          $i=1;
	  foreach($this->RabiCrop as $keyrb)
	  {
	?>
        <tr>
          <td><?php echo $keyrb['RabiCrop'];?></td>
       
          <td><a href="/appsetting/edit-key/key/lastrabi/code/<?php echo md5($keyrb['id']);?>"><i class="icon-pencil"></i></a> 
|  <a href="javascript:void(0);" onclick="deleteAppsetting('<?php echo md5($keyrb['id']);?>','lastrabi')" ><i class="icon-remove"></i></a>
          </td>
        </tr>

           <?php } } else { ?>  
	   <tr><td colspan="8">Result not found.</td></tr>
	   <?php } ?>

      </tbody>
    </table>
</div>
     
     <div class="well" style="overflow:scroll; height:220px; width: 46% !important; float: left! important; margin: 4px;" >
    <a href="/appsetting/add-key/key/lastkharif" class="btn btn-primary" style="float:right; margin-bottom: 4px;">Add Last Kharif Crop</a>
    <table class="table tablesorter">
      <thead>

	  <tr><td colspan="13" class="tableheading">Manage Last Kharif Crop</td></tr>
        <tr>
<th>Kharif Crop</th>

<th>Action</th>
 </tr>
      </thead>
      <tbody>
       <?php
	   	
	if($this->KharifCrop)
	{
          $i=1;
	  foreach($this->KharifCrop as $keykr)
	  {
	?>
        <tr>
          <td><?php echo $keykr['KharifCrop'];?></td>
       
          <td><a href="/appsetting/edit-key/key/lastkharif/code/<?php echo md5($keykr['id']);?>"><i class="icon-pencil"></i></a> 
|  <a href="javascript:void(0);" onclick="deleteAppsetting('<?php echo md5($keykr['id']);?>','lastkharif')" ><i class="icon-remove"></i></a>
          </td>
        </tr>

           <?php } } else { ?>  
	   <tr><td colspan="8">Result not found.</td></tr>
	   <?php } ?>

      </tbody>
    </table>
</div>
     
     
      <div class="well" style="overflow:scroll; height:220px; width: 46% !important; float: left! important; margin: 4px;" >
    <a href="/appsetting/add-key/key/soiltype" class="btn btn-primary" style="float:right; margin-bottom: 4px;">Add Soil Type</a>
    <table class="table tablesorter">
      <thead>

	  <tr><td colspan="13" class="tableheading">Manage Soil Type</td></tr>
        <tr>
<th>Soil Type</th>

<th>Action</th>
 </tr>
      </thead>
      <tbody>
       <?php
	   	
	if($this->SoilType)
	{
          $i=1;
	  foreach($this->SoilType as $keyr)
	  {
	?>
        <tr>
          <td><?php echo $keyr['SoilType'];?></td>
       
          <td><a href="/appsetting/edit-key/key/soiltype/code/<?php echo md5($keyr['id']);?>"><i class="icon-pencil"></i></a> 
|  <a href="javascript:void(0);" onclick="deleteAppsetting('<?php echo md5($keyr['id']);?>','soiltype')" ><i class="icon-remove"></i></a>
          </td>
        </tr>

           <?php } } else { ?>  
	   <tr><td colspan="8">Result not found.</td></tr>
	   <?php } ?>

      </tbody>
    </table>
</div>
</div>
</div>
</div>
    
   
