<?php
$auth = Zend_Auth::getInstance();
$authStorage = $auth->getStorage();
$params = $this->params;
$circleList = $this->circleList;
$districtList = $this->districtList;

?>




<link rel="stylesheet" href="/css/datepicker/jquery.ui.all.css">

<script src="/js/jquery-1.8.3.js"></script>

<script type="text/javascript" src="/js/jquery.timepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery.timepicker.css" />
<script type="text/javascript" src="/lib2/bootstrap-datepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/lib2/bootstrap-datepicker.css" />

<script src="/js/jquery.ui.core.js"></script>
<script src="/js/jquery.ui.widget.js"></script>
<script src="/js/jquery.ui.datepicker.js"></script>
<script type="text/javascript">
$(function() {
$( "#district_id" ).change(function(e) {   
$.get( "/region/get-alltehsil-by-district", { district_id: $( "#district_id" ).val() }, "json" )
.done(function( data ) {
  select = document.getElementById('tehsil_id');
  select.options.length = 0;
  options = data.options; // Or whatever source information you're working with
    for (index = 0; index < options.length; ++index) { 
      option = options[index];
      select.options.add(new Option(option.text, option.value));
    }	
});
});

$( "#tehsil_id" ).change(function(e) {   
$.get( "/village/get-allregion-by-tehsil", { tehsil_id: $( "#tehsil_id" ).val() }, "json" )
.done(function( data ) {
  select = document.getElementById('region_id');
  select.options.length = 0;
  options = data.options; // Or whatever source information you're working with
    for (index = 0; index < options.length; ++index) { 
      option = options[index];
      select.options.add(new Option(option.text, option.value));
    }	
});
});


		
});
</script>
<script>
$(function() {
		$( "#dob" ).datepicker({
			showOn: "button",
			buttonImage: "http://runapp.me/images/calendar.gif",
			dateFormat: 'yy-mm-dd',
			buttonImageOnly: true,
			buttonText:'Date Of Birth',
                        changeMonth: true,
                        changeYear: true
		});
			
               
              
});



function validateUser()
{  
        if(document.getElementById("staffname").value=="")
	{
	 alert("Please enter field executive name.");
	 document.getElementById("staffname").focus();
	 return false;
	}
	
	if(document.getElementById("phone").value=="")
	{
	 alert("Please enter field executive mobile no.");
	 document.getElementById("phone").focus();
	 return false;
	}
        
        if(document.getElementById("circle_id").value=="")
	{
	 alert("Please select circle name");
	 document.getElementById("circle_id").focus();
	 return false;
	}
        
        if(document.getElementById("district_id").value=="")
	{
	 alert("Please select district name.");
	 document.getElementById("district_id").focus();
	 return false;
	}
       if(document.getElementById("tehsil_id").value=="")
	{
	 alert("Please select tehsil name.");
	 document.getElementById("tehsil_id").focus();
	 return false;
	}
        
          if(document.getElementById("region_id").value=="")
	{
	 alert("Please select region name.");
	 document.getElementById("region_id").focus();
	 return false;
	}
        
  return true;
}
          
 function setVillageList(str)
 {
   if (window.XMLHttpRequest) {
     xmlhttp=new XMLHttpRequest();
   }
   else{
     xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
   }
  xmlhttp.onreadystatechange=function()
  {
      if (xmlhttp.readyState==4 && xmlhttp.status==200)
      {
         document.getElementById("villageList").innerHTML=xmlhttp.responseText;
      }
   }
 xmlhttp.open("GET","/user/village-list/region_id/"+str,true);
 xmlhttp.send();

}           
</script>




<div class="content">
        
        <div class="header">
            <h1 class="page-title">Add New Field Executive </h1>
        </div>
        
        <ul class="breadcrumb">
            <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
			<li class="active">Manage Users<span class="divider">/</span></li>
           
        </ul>
<?php if($this->successMessage) { ?>
		<div class="alert alert-info">
				<button data-dismiss="alert" class="close" type="button">×</button>
				<?php echo $this->successMessage;?>
		</div>	
		<?php } ?>
		
		<?php if($this->errorMessage) { ?>
		<div class="alert alert-error">
			<button data-dismiss="alert" class="close" type="button">×</button>
			<?php echo $this->errorMessage;?>
		</div>
	   <?php } ?>
	<div class="well" style="padding:0 10px; width:auto;   margin-left: 10px;
  margin-right: 10px;
  -webkit-border-radius: 10px!important;">
             
      
       <form id="myform" method="post" name="fielduserform" action="/user/add-fielduser"  onsubmit="return validateUser();"  >
            <fieldset>
            <legend>FE Personal Details</legend>
              <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">FE Name :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <input type="text" value="" name="staffname" id="staffname" placeholder="Field Executive name...."> 
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">FE Email :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <input type="text" value="" name="email" id="email" placeholder="Field Executive email...."> 
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            
            
             <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">FE Mobile No. :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <input type="text" value="" name="phone" id="phone" placeholder="Field Executive phone no...."> 
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">FE DOB :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <input type="text" value="" name="dob" id="dob" placeholder="Field Executive date of birth...."> 
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
               <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">FE Current Address :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <textarea name="current_address" placeholder="Field Executive current address...."></textarea>
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">FE Permanent Address :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <textarea name="permanent_address" placeholder="Field Executive permanent address...."></textarea>
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            
         
             <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">Gender :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <input type="radio" value="M" name="gender" checked=""> Male
                     <input type="radio" value="F" name="gender"> Female
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
           
            
            </fieldset>
           
         <!--  
           <fieldset>
            <legend>FE Official Details</legend>
            
            <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">Circle Name :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <select name="circle_id" id="circle_id" style="width:222px !important;">
                         <option value="">--Select Circle--</option>
                         <option value="<?php echo $circleList['id'];?>" selected=""><?php echo $circleList['state'];?> [<?php echo $circleList['Circle'];?>]</option>   
                     </select>
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            
            <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">District Name :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <select name="district_id" id="district_id" style="width:222px !important;">
                         <option value="">--Select District--</option>
                         <?php
                         foreach($districtList as $district){
                             ?>
                          <option value="<?php echo $district['id']?>"><?php echo $district['district_name']?></option>
                             <?php
                         }
                         ?>
                     </select>
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            
            
             <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">Tehsil Name :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <select name="tehsil_id" id="tehsil_id" style="width:222px !important;">
                         <option value="">--Select Tehsil--</option>
                         
                     </select>
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            
          
            
            
            
            
            <div class="frmRow" style="float: left; width: 50%;" >
            	<div class="frmColLeft" style="width:170px !important;">Region Name :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <select name="region_id" id="region_id" style="width:222px !important;" onchange="setVillageList(this.value)">
                         <option value="">--Select Region--</option>
                         
                     </select>
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            
                
            
            
            
           </fieldset> 
           <div  id="villageList">
            	
            </div> -->
         
              <div class="genrateBtn" style="margin-left:170px !important; margin-top: 25px; padding-bottom:35px; ">
              <button type="button" class="btn btn-primary" value="Cancel">Cancel</button>
              <button type="submit" class="btn btn-primary" value="Save">Add Field User</button>
              </div>
        </form>
</div>
    </div>



