<?php
$auth = Zend_Auth::getInstance();
$authStorage = $auth->getStorage();
$params = $this->params;


$userDetails=$this->userDetails;


//echo '<pre>';
//print_r($this->viilist);
//echo '</pre>';
//exit();
?>




<link rel="stylesheet" href="/css/datepicker/jquery.ui.all.css">

<script src="/js/jquery-1.8.3.js"></script>

<script type="text/javascript" src="/js/jquery.timepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery.timepicker.css" />
<script type="text/javascript" src="/lib2/bootstrap-datepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/lib2/bootstrap-datepicker.css" />

<script src="/js/jquery.ui.core.js"></script>
<script src="/js/jquery.ui.widget.js"></script>
<script src="/js/jquery.ui.datepicker.js"></script>
<script type="text/javascript">.js"></script>
<script type="text/javascript">

<script>
$(function() {
		$( "#dob" ).datepicker({
			showOn: "button",
			buttonImage: "http://runapp.me/images/calendar.gif",
			dateFormat: 'yy-mm-dd',
			buttonImageOnly: true,
			buttonText:'Date Of Birth',
                        changeMonth: true,
                        changeYear: true
		});
			    
});



function validateUser()
{  
        if(document.getElementById("staffname").value=="")
	{
	 alert("Please enter field executive name.");
	 document.getElementById("staffname").focus();
	 return false;
	}
	
	if(document.getElementById("phone").value=="")
	{
	 alert("Please enter field executive mobile no.");
	 document.getElementById("phone").focus();
	 return false;
	}
}
          
 


 
     
</script>




<div class="content">
        
        <div class="header">
            <h1 class="page-title">Edit Field Executive </h1>
        </div>
        
        <ul class="breadcrumb">
            <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
			<li class="active">Manage Users<span class="divider">/</span></li>
           
        </ul>
<?php if($this->successMessage) { ?>
		<div class="alert alert-info">
				<button data-dismiss="alert" class="close" type="button">×</button>
				<?php echo $this->successMessage;?>
		</div>	
		<?php } ?>
		
		<?php if($this->errorMessage) { ?>
		<div class="alert alert-error">
			<button data-dismiss="alert" class="close" type="button">×</button>
			<?php echo $this->errorMessage;?>
		</div>
	   <?php } ?>
	<div class="well" style="padding:0 10px; width:auto;   margin-left: 10px;
  margin-right: 10px;
  -webkit-border-radius: 10px!important;">
             
      
       <form id="myform" method="post" name="fielduserform" action="/user/edit-fielduser"  onsubmit="return validateUser();"  >
         <input type="hidden" name="user_id" value="<?php echo $params['datacode']?>"> 
           
            <fieldset>
            <legend>FE Personal Details</legend>
              <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">FE Name :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <input type="text" value="<?php echo $userDetails['StaffName']?>" name="staffname" id="staffname" placeholder="Field Executive name...."> 
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">FE Email :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <input type="text" value="<?php echo $userDetails['Email']?>" name="email" id="email" placeholder="Field Executive email...."> 
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            
            
             <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">FE Mobile No. :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <input type="text" value="<?php echo $userDetails['MobileNo']?>" name="phone" id="phone" placeholder="Field Executive phone no...."> 
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">FE DOB :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <input type="text" value="<?php echo $userDetails['DOB']?>" name="dob" id="dob" placeholder="Field Executive date of birth...."> 
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
               <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">FE Current Address :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <textarea name="current_address" placeholder="Field Executive current address...."><?php echo $userDetails['Address_Curr']?></textarea>
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">FE Permanent Address :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <textarea name="permanent_address" placeholder="Field Executive permanent address...."><?php echo $userDetails['Address_Per']?></textarea>
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
            
         
             <div class="frmRow" style="float: left; width: 50%;">
            	<div class="frmColLeft" style="width:170px !important;">Gender :</div>
                <div class="frmColRight" style="margin-left: 170px!important;">
            	<div class="acme_dtdp">
                 <div style="width:250px !important;">
                     <input type="radio" value="M" name="gender" <?php if($userDetails['Gender']=='M'){ echo 'checked';}?>> Male
                     <input type="radio" value="F" name="gender" <?php if($userDetails['Gender']=='F'){ echo 'checked';}?>> Female
                  </div>
                </div>
            	</div>
                
				 <div class="clear"></div>
            </div>
           
            
            </fieldset>
           
           
         
              <div class="genrateBtn" style="margin-left:10px !important; margin-top: 25px; padding-bottom:35px; ">
            
              <button type="submit" class="btn btn-primary" value="Save">Update Field User</button>
              </div>
        </form>
</div>
    </div>



