<?php 
$record = $this->paginator; 
$totalrec = $this->totalrec;
$get = $this->get;
$params = $this->params;

// Start reset url code
$auth = Zend_Auth::getInstance();
$authStorage = $auth->getStorage();
//echo "<pre>"; print_r($authStorage->read()); die;
$role = $authStorage->read()->Role;


?>

<script type="text/javascript">
function goback() {
    history.go(-1);
}
</script>




<!-- Search ajax end here -->

<div class="content">
        
        <div class="header">
            <h1 class="page-title">Manage Users </h1>
        </div>
        <div class="breadcrumb">
        <div style="position:relative;">
        <ul class="imop">
            <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
            <li class="active">Manage Users</li> 
        </ul>
        <?php if($params['type']=='sucess') { ?>
		<div class="alert alert-info">
				<button data-dismiss="alert" class="close" type="button">×</button>
				Field executive has been successfully updated
		</div>	
		<?php } ?>
		
		
        </div>
        <a href="javascript:void(0);" style="position:absolute; right:10px; top:5px; border: 1px solid; background-color: #4d5b76; color: #fff; padding:1px 6px; font-size:12px; font-weight:bold; display:block;" id="showuserlocation" class="iframe" onClick="goback();">Back</a>
        </div>
<script>
$(document).ready(function() {
    $('.breadcrumb').css({'width':(($(window).width())-270)+'px'});
	$(window).resize(function(){
       $('.breadcrumb').css({'width':(($(window).width())-270)+'px'}); 
    });
});
</script>





<style>
.tableheading{
	background-color: #e2e2e2;
	color: #000;
	font-weight: bold;
	text-align: center;
	padding-bottom: 5px;
	border-bottom: 1px solid #cfcccc;
}
.txt_center{
	text-align:center !important;
}
.imop{
margin:0px !important;
}
</style>
        <div class="container-fluid" style="padding-top:162px;">

<!--- user filtor by role end --->

 <div class="row-fluid" style="margin-top:10px;">
                    
<div class="search-well">
	<div class="form-inline">
	<form class="form-inline" style="width:870px; float: left;" method="get" action="" style="margin-bottom:10px;">
		<input type="text" name="search" id="search" placeholder="Search Here..." value="<?php echo $get['search'];?>" class="input-large">
		<input type="hidden" name="staffCode" id="staffCode" value="<?php echo $this->supervisorStaffCode;?>">
		<button type="submit" class="btn" id="searchbtn" style="position:relative; text-align:center; padding-left:22px;"><span class="search"></span> Go</button>
		<button type="button" class="btn" > Reset</button>
		</form>
            <a href="/user/add-fielduser" class="btn btn-primary">Add New Field Executive</a>
	</div>
</div>

<div class="alert alert-info" id="user_del_message" style="display:none;">
		<button data-dismiss="alert" class="close" type="button">×</button>
		User device info clear successfully.
	</div>
			
<div class="well" style="overflow:scroll; height:auto;">
    <table class="table tablesorter">
      <thead>

	  <tr><td colspan="13" class="tableheading">Manage Field Executives</td></tr>
        <tr>
<th>Name </th>
<th>Login ID</th>
<th>Email </th>
<th>Mobile No.</th>
<th>Track Path</th>
<th>View Log</th>
<th>Total Amount</th>
<th>Paid Amount</th>
<th>Remaining Amount</th>
<th class="txt_center">Total farmers</th>
<th>Action</th>
 </tr>
      </thead>
      <tbody>
       <?php
	   	
	if($totalrec)
	{
          $i=1;
	  foreach($record as $key=>$val)
	  {
	$frmmster = new Application_Model_Farmermasters();
        $TotamountaganistEnggInSeed = $frmmster->TotamountaganistEnggInSeed($val['LoginID']);
        $TotamountaganistEnggInChemical = $frmmster->TotamountaganistEnggInChemical($val['LoginID']);
        
        $Tot = $TotamountaganistEnggInSeed['tot_seed'] + $TotamountaganistEnggInChemical['tot_chl'];
        $Tot_paid = $TotamountaganistEnggInSeed['tot_seed_rcv'] + $TotamountaganistEnggInChemical['tot_chl_rcv'];
        $remaining = $Tot - $Tot_paid;
        $arrTotalFarmer = $frmmster->getFarmerCount($val['LoginID']);
        
         ?>
        <tr>
          <td><?php echo $val['StaffName'];?></td>
          <td><?php echo $val['LoginID'];?></td>
          <td><?php echo $val['Email'];?></td>
	  <td><?php echo $val['MobileNo'];?></td>
	  <th class="txt_center"></th>
          <th class="txt_center"></th>
         <td><?php if($Tot !='0'){ echo $Tot;} else{ echo '0'; }?></td>
          <td><?php if($Tot_paid !='0'){ echo $Tot_paid;}else{ echo '0';}?></td>
          <td><?php if($remaining !='0'){echo $remaining;}else{ echo '0';}?></td>
          <th class="txt_center"> <a href="/myfarmer/view-farmer-list/datacode/<?php echo md5($val['LoginID']);?>" title="View Farmers">View </a> (<?php echo  $arrTotalFarmer['totalfarmer'];?>) </th>		 
        <td> 
			<a href="/user/edit-fielduser/datacode/<?php echo $val['LoginID'];?>" title="View Farmers">Edit </a> | 
        <a href="/user/view-mapping-list/datacode/<?php echo $val['LoginID'];?>" title="View Farmers">Village Mapping </a>
        </td>

           <?php } } else { ?>  
	   <tr><td colspan="8">Result not found.</td></tr>
	   <?php } ?>

      </tbody>
    </table>
</div>

<!--Pagingnation Start-->
<?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); } ?>
	</div>
</div>
</div>
    
   
