<?php 
$record = $this->paginator; 
$totalrec = $this->totalrec;
$get = $this->get;
$params = $this->params;

// Start reset url code
$auth = Zend_Auth::getInstance();
$authStorage = $auth->getStorage();
//echo "<pre>"; print_r($authStorage->read()); die;
$role = $authStorage->read()->Role;


?>

<script type="text/javascript">
function goback() {
    history.go(-1);
}

function changeStatus(userId){
     swal({
        title: "Are you sure?",
        text: "You want to delete this user",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "Yes, delete it!",
        closeOnConfirm: false
    }, function (isConfirm) {
        if (!isConfirm) return;
        $.ajax({
           url: "/user/delete-user/userId/"+userId,
            type: "GET",
            dataType: "html",
            success: function () {
              swal({
                title: "delete", 
                text: "user has been successfully deleted", 
                type: "success"
              },function() {
                location.reload();
              });
            },
            error: function (xhr, ajaxOptions, thrownError) {
                swal("Error "+status+"!", "Please try again", "error");
            }
        });
    });
  };
</script>




<!-- Search ajax end here -->

<div class="content">
        
        <div class="header">
            <h1 class="page-title">Manage Users </h1>
        </div>
        <div class="breadcrumb">
        <div style="position:relative;">
        <ul class="imop">
            <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
            <li class="active">Manage Users</li> 
        </ul>
        <?php if($params['type']=='sucess') { ?>
		<div class="alert alert-info">
				<button data-dismiss="alert" class="close" type="button">×</button>
				Field executive has been successfully updated
		</div>	
		<?php } ?>
		
		
        </div>
        <a href="javascript:void(0);" style="position:absolute; right:10px; top:5px; border: 1px solid; background-color: #4d5b76; color: #fff; padding:1px 6px; font-size:12px; font-weight:bold; display:block;" id="showuserlocation" class="iframe" onClick="goback();">Back</a>
        </div>
<script>
$(document).ready(function() {
    $('.breadcrumb').css({'width':(($(window).width())-270)+'px'});
	$(window).resize(function(){
       $('.breadcrumb').css({'width':(($(window).width())-270)+'px'}); 
    });
});
</script>





<style>
.tableheading{
	background-color: #e2e2e2;
	color: #000;
	font-weight: bold;
	text-align: center;
	padding-bottom: 5px;
	border-bottom: 1px solid #cfcccc;
}
.txt_center{
	text-align:center !important;
}
.imop{
margin:0px !important;
}
</style>
        <div class="container-fluid" style="padding-top:162px;">

<!--- user filtor by role end -->

 <div class="row-fluid" style="margin-top:10px;">
                    
<div class="search-well">
	<div class="form-inline">
	
            <a href="/user/add-fielduser" class="btn btn-primary" >Add New User</a>
	</div>
</div>

<div class="alert alert-info" id="user_del_message" style="display:none;">
		<button data-dismiss="alert" class="close" type="button">×</button>
		User device info clear successfully.
	</div>
			
<div class="well" style="overflow:scroll; height:auto;">
    <table class="table tablesorter">
      <thead>

	  <tr><td colspan="13" class="tableheading">Manage Field Executives</td></tr>
        <tr>
<th>Name </th>
<th>Login ID</th>
<th>Email </th>
<th>Mobile No.</th>
<th >View Contact Information</th>
<th >View Place Information</th>
<th>Action</th>
 </tr>
      </thead>
      <tbody>
       <?php
	   	
	if($totalrec){
          $i=1;
	  foreach($record as $key=>$val){
	
        
         ?>
        <tr>
          <td><?php echo $val['StaffName'];?></td>
          <td><?php echo $val['LoginID'];?></td>
          <td><?php echo $val['Email'];?></td>
	  <td><?php echo $val['MobileNo'];?></td>	
          <td><a href="/user/view-contact/datacode/<?php echo md5($val['LoginID']);?>" title="View Contact Information">View </a></td>
          <td><a href="/user/view-place/datacode/<?php echo md5($val['LoginID']);?>" title="View Plac Information">View </a></td>	
         <td> 
	    <a href="/user/edit-fielduser/datacode/<?php echo $val['LoginID'];?>" title="Edit">Edit </a>
      |
       <a href="javascript:void(0)" onclick="changeStatus('<?php echo $val['LoginID'];?>')" title="Delete">Delete </a>
        </td>

           <?php } } else { ?>  
	   <tr><td colspan="8">Result not found.</td></tr>
	   <?php } ?>

      </tbody>
    </table>
</div>

<!--Pagingnation Start-->
<?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); } ?>
	</div>
</div>
</div>
    
   
