<?php 
$get = $this->get;
$params = $this->params;
//$allLands = $this->allLands;

$getLoginUserInformation = $this->getLoginUserInformation;

$record = $this->paginator; 
$totalrec = $this->totalrec;


?>

    
<script type="text/javascript">
function goback() {
    history.go(-1);
}
</script>

<!-- fancybox start here -->
<script type="text/javascript" src="/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<script type="text/javascript">
	$(document).ready(function() {	
				$("a#view-details").fancybox({
				'transitionIn'	:	'elastic',
				'transitionOut'	:	'elastic',
				'width' : 800,
				'height' : 500,
				'speedIn'		:	600, 
				'speedOut'		:	200, 
				'overlayShow'	:	true
				});	
			});
			
			$(document).ready(function() {	
					$("a#showfarmerpopups").fancybox({
					'width' : "80%",
					'height' : "80%",
					'speedIn'		:	600, 
					'speedOut'		:	200, 
					'overlayShow'	:	true
					});	
				});	


					
</script> 

<div class="content">
        
        <div class="header">
            <h1 class="page-title">Manage Users </h1>
        </div>
        <div class="breadcrumb">
        <div style="position:relative;">
        <ul class="imop">
            <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
            <li class="active">View Place Information</li> 
        </ul>
        <?php if($params['type']=='sucess') { ?>
		<div class="alert alert-info">
				<button data-dismiss="alert" class="close" type="button">×</button>
				Field executive has been successfully updated
		</div>	
		<?php } ?>
		
		
        </div>
        <a href="javascript:void(0);" style="position:absolute; right:10px; top:5px; border: 1px solid; background-color: #4d5b76; color: #fff; padding:1px 6px; font-size:12px; font-weight:bold; display:block;" id="showuserlocation" class="iframe" onClick="goback();">Back</a>
        </div>
<script>
$(document).ready(function() {
    $('.breadcrumb').css({'width':(($(window).width())-270)+'px'});
	$(window).resize(function(){
       $('.breadcrumb').css({'width':(($(window).width())-270)+'px'}); 
    });
});
</script>





<style>
.tableheading{
	background-color: #e2e2e2;
	color: #000;
	font-weight: bold;
	text-align: center;
	padding-bottom: 5px;
	border-bottom: 1px solid #cfcccc;
}
.txt_center{
	text-align:center !important;
}
.imop{
margin:0px !important;
}
</style>
        <div class="container-fluid" style="padding-top:162px;">

<!--- user filtor by role end --->

 <div class="row-fluid" style="margin-top:10px;">
                    

<div style="  display:block; background-color:#E0FFFF; width:20%; padding:11px; ">
   <b>Total Place Information : <?php echo $totalrec;  ?> </b>
</div>
    
<div class="well" style="overflow:scroll; height:auto;">
    
    <table class="table tablesorter">
      <thead>

	  <tr><td colspan="13" class="tableheading">Place Information Detail</td></tr>
        <tr>
       
                                           <td>S.No.</td>
                                            <td>Place Description</td>
                                            <td>Concerned Person </td>
                                            <td>Designation</td>
                                            <td>Contact</td>
                                            <td>Address</td>
                                            <td>Date</td>   

 </tr>
      </thead>
      <tbody>
       <?php
	   	
	if($totalrec){
          $i=1;
	  foreach($record as $key=>$val){
	
        
         ?>
        <tr>
     
                                                                <td><?php echo $i; ?></td>        
                                                                <td><?php echo ucfirst($val['place_description']);?></td>
                                                                <td><?php echo ucfirst($val['consenred_person']);?></td>
                                                                <td><?php echo ucfirst($val['designation']);?></td>
                                                                <td><?php echo ucfirst($val['contact']);?></td>   
                                                                <td><?php echo ucfirst($val['address']);?></td>
                                                                <td><?php echo ucfirst($val['date(offline_sink_datetime)']);?></td>   


           <?php  $i++; } } else { ?>  
	   <tr><td colspan="8">Result not found.</td></tr>
	   <?php } ?>

      </tbody>
    </table>
</div>

<!--Pagingnation Start-->
<?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); } ?>
	</div>
</div>
</div>
    
   
