<!-- Form validation script start here -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="/js/jquery.validate.min.js"></script>
<script type="text/javascript">
(function($,W,D)
{
    var JQUERY4U = {};

    JQUERY4U.UTIL =
    {
        setupFormValidation: function()
        {
            //form validation rules
            $("#change-pass").validate({
                rules: {
				    old_pass: "required",
                    password: "required",
                    cpassword: {
                        required: true,
                        equalTo: "#password"
                    }
                },
                messages: {
				    old_pass: "Please enter current password",
                    password: "Please enter new password",
					cpassword: {
                        required: "Please enter confirm password",
						equalTo: "Please enter the same password as above"
                    }
                },
                submitHandler: function(form) {
                    form.submit();
                }
            });
        }
    }

    //when the dom has loaded setup form validation rules
    $(D).ready(function($) {
        JQUERY4U.UTIL.setupFormValidation();
    });

})(jQuery, window, document);
</script>
<style>
#change-pass label.error {
    color: #FB3A3A;
    /* display: inline-block;
    margin: 4px 0 5px 5px; */
    padding: 0;
    width: 310px;
}
</style>
<!-- Form validation script end here -->

<style>
li {list-style:none; color:#ed3237; font-size:13px;}
ul{margin:0px; padding:0px;}
</style>
<?php $form = $this->form;?>

<div class="content">
        
        <div class="header">
            
            <h1 class="page-title">Change Password</h1>
        </div>
        
        <ul class="breadcrumb">
            <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
            <li class="active">Change Password </li>
        </ul>

        <div class="container-fluid">
            <div class="row-fluid">
			
	        <?php if($this->successMessage) { ?>
		    <div class="alert alert-info">
				<button data-dismiss="alert" class="close" type="button">×</button>
				<?php echo $this->successMessage;?>
		    </div>	
		    <?php } ?>
		
		<?php if($this->errorMessage) { ?>
		<div class="alert alert-error">
			<button data-dismiss="alert" class="close" type="button">×</button>
			<?php echo $this->errorMessage;?>
		</div>
	   <?php } ?>

<div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#send-notification" data-toggle="tab">Change Password</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane active in" id="home">
   
   <form method="post" id="change-pass" action="/admin/change-password">
       	
        <label>Current Password</label>
		<?php echo $form->old_pass;?>
		<label>New Password</label>
		<?php echo $form->password;?>
		 <label>Confirm Password</label>
		<?php echo $form->cpassword;?>
	
	<div style="margin:5px; 0px; margin-left:0px;">
       <button class="btn btn-primary" type="submit">Submit</button>
     </div>
	 
    </form>
	
      </div>

  </div>

</div>

        
	</div>
</div>
</div>
    


    
