<style>
li {list-style:none; color:#ed3237; font-size:13px;}
ul{margin:0px; padding:0px;}
</style>
<?php $form = $this->form;?>
    
<div class="row-fluid">
    <div class="dialog">
        <div class="block">
            <p class="block-heading">Forgot your password</p>
            <div class="block-body">
             <p style="color:red;"><?php echo $this->errorMessage;?></p>
                <form method="post" action="/admin/forgotpassword">
                    <label>Email Address</label>
                     <?php echo $form->email;?>
                     <input name="submit" class="btn btn-primary pull-right" value="Send" type="submit">
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
        <a href="/admin">Sign in to your account</a>
    </div>
</div>


