<?php 
$record = $this->paginator; 
$totalrec = $this->totalrec;
$get = $this->get;
?>
 <!-- fancybox start here -->
<script type="text/javascript" src="/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
 <script type="text/javascript">
		$(document).ready(function() {	
					$("a#checkdocument").fancybox({
					'transitionIn'	:	'elastic',
					'transitionOut'	:	'elastic',
					'width' : 1000,
					'height' : 800,
					'speedIn'		:	600, 
					'speedOut'		:	200, 
					'overlayShow'	:	true
					});	
				});	
</script> 

<!-- fancybox end here -->
<script type="text/javascript">
$(function(){
	$("#filtorUser").change(function(){
		var filval = $(this).val();
		if(filval)
		{
			window.location = '/admin/home/filtorUser/'+filval; 
			return false;
		}
		else
		{
			window.location = '/admin/home'; 
		}
	});
	
	$("#searchbtn").click(function(){
		var search = $("#search").val();
		if(!search)
		{
			alert('Please enter search text');
			return false;
		}
		window.location = '/admin/home/search/'+search; 
	});
});

$(function(){
	$("a#chaangestatus").live("click",function(){
		var obj = $(this);
		var id = obj.attr("rel");
		$.get("/admin/pass",{action:"changeStatus",rowid:id},function(data){
			if(data == 3)
			{
				alert("This user on trip. You can't delete this user.");
				return false;
			}
			if(data == '1')
			{
				obj.html('<img src="/images/icon_active.gif">');
				obj.attr({'title':'active'});
			}
			else
			{
				obj.html('<img src="/images/icon_diaprove.gif">');
				obj.attr({'title':'Inactive'});
			}
		});
	});
	
	
	$("a#deleteUser").live("click",function(){
	if(!confirm('Are sure want to delete this user.'))
	{
		return false;
	}
		var obj = $(this);
		var id = obj.attr("rel");
		$.get("/admin/pass",{action:"deleteUser",rowid:id},function(data){ 
		alert(data);
			if(data == 3)
			{
				alert("This user on trip. You can't delete this user.");
				return false;
			}
			if(data == 'success')
			{
				window.location.reload();
			}
			else
			{
				alert(data);
			}			
		});
	});
	
});
</script>
<style>
a.docfiltor{
	padding: 5px;
	width: 5px;
	background-color: #f2f2f2;
	border: 1px solid;
}
a.docactive{
background-color: #000 !important;
color: #fff !important;
}
}
</style>
 <div id="container" class="round10">

   <div id="header" class="">
           <div class="left"><a href="/admin/home"></a></div>
          
                      <div class="right" id="adminBtns" align="right">
               
               <div class="right" align="center">
                   <a href="/admin/logout">
                   <img src="/images/logout.png" alt="Logout" style="width:26px; height:26px;"></a>
                   <a href="/admin/logout" style="color:white;">Logout</a>
               </div>
           </div>
          
            <div class="clear"></div>
            <div class="right" id="loginDetails">User Logged In: admin</div>
            <div class="clear"></div>
                        <div class="clear"></div>
      </div>
      <div class="clear"></div>

      <div id="sidebar" class="left" style="border-radius:none;" align="center">
<ul class="navlinks">
<li><a href="/admin/home" class="active">Home</a></li>
<li><a href="/supervisor/">Manage Supervisor </a></li>
</ul>
         
</div>  
      <div class="clear"></div>

<div id="content" class="round10">
         <h1>User List &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
		 
        </h1>
<div style="float:left;">
<select id="filtorUser">
<option value="">ALL</option>
<option value="driver" <?php if($get['filtorUser'] == 'driver'){?> selected="selected"<?php }?>>Driver</option>
<option value="customer" <?php if($get['filtorUser'] == 'customer'){?> selected="selected"<?php }?>>Customer</option>
</select><br>
   <?php 
   @session_start();
   echo $_SESSION['msg']; 
   unset($_SESSION['msg']);
   ?>
</div>
    <div style="padding-bottom:5px; float:right;">
	<a href="/admin/home" class="docfiltor <?php if(!$get['docstatus']){?>docactive<?php }?>">ALL</a>
	<a href="/admin/home/docstatus/Approved" class="docfiltor <?php if($get['docstatus'] == 'Approved'){?>docactive<?php }?>">Approved</a>
	<a href="/admin/home/docstatus/Pending" class="docfiltor <?php if($get['docstatus'] == 'Pending'){?>docactive<?php }?>">Pending</a>
	<a href="/admin/home/docstatus/Declined" class="docfiltor <?php if($get['docstatus'] == 'Declined'){?>docactive<?php }?>">Declined</a>
	<br />
	<input type="text" name="search" id="search" style="border-radius:6px; margin-top: 9px;" placeholder="Search" value="<?php echo $get['search'];?>">
	<input type="button" value="Search" id="searchbtn" style="padding:4px;"> 
	</div>	 	  
      
   		<div style="clear:both;"></div>
   		 <div class="tab_container">
			<table class="tablesorter" cellspacing="0" width="100%"> 
			<thead> 
				<tr> 
				<th class="header" align="center" valign="top" width="15%" style="line-height: 16px;">Name</th>
      			<th class="header" align="center" valign="top" width="10%" style="line-height: 16px;">Current Role </th>
      			<th class="header" align="center" valign="top" width="15%">Phone Number</th>
                <th class="header" align="center" valign="top" width="15%">Email</th>
      			<th class="header" align="center" valign="top" width="10%" style="line-height: 16px;">Current Status</th>
				<th class="header" align="center" valign="top" width="10%" style="line-height: 16px;">View Document</th>
				<th class="header" align="center" valign="top" width="10%" style="line-height: 16px;">Document Status</th>
				<th class="header" align="center" valign="top" width="10%">Action</th>
   				</tr> 
			</thead> 
							<tbody>
			
            <?php
			if($totalrec)
			{
				foreach($record as $key=>$val)
				{
					?>
					<tr id="<?php echo md5('idsalt'.$val['user_id']);?>"> 
				<td align="center"><?php echo $val['name'];?></td>
                 <td align="center"><?php echo $val['current_role'];?></td>
                <td align="center"><?php echo $val['phone_number'];?></td>
               <td align="center"><?php echo $val['email'];?></td>
			   <td align="center">
			   <?php 
				if($val['as_driver_id'])
				{
					echo $val['driver_status']?'<b>Active</b>':'<b>Inactive</b>';
				}
				else
				{
					echo '---';
				}
			   ?></td>
			   <td align="center">
			   <?php
				if($val['as_driver_id'])
				{
					?>
		<a href="/admin/driver-document/docid/<?php echo md5('idsalt'.$val['as_driver_id']);?>" id="checkdocument" class="iframe"><div style="border: 1px solid;
color: #fff;
background-color: #000;
font-weight: bold;">View</div>
</a>
					<?php
				}else{ echo '---'; }
			   ?>
			   </td>
			   <td align="center">
			   <?php 
				if($val['as_driver_id'])
				{
					if($val['admin_apporve'] == 0)
					{
						echo 'Pending';
					}
					else if($val['admin_apporve'] == 1)
					{
						echo 'Approved';
					}
					else
					{
						echo 'Declined';
					}		
					
				}
				else
				{
					echo '---';
				}
				?>
			   </td>
				<td align="center">
				<?php
					if($val['access_status'] == 1)
					{
				?>
     			    <a href="javascript:void(0);" title="Active" id="chaangestatus" rel="<?php echo md5('idsalt'.$val['user_id']);?>"><img src="/images/icon_active.gif"></a>
				   <?php }else{?>
				    <a href="javascript:void(0);" title="Inactive" id="chaangestatus" rel="<?php echo md5('idsalt'.$val['user_id']);?>"><img src="/images/icon_diaprove.gif"></a>
				   <?php }?>
   				    <a href="javascript:void(0);" title="Delete" id="deleteUser"  rel="<?php echo md5('idsalt'.$val['user_id']);?>"><img src="/images/icn_trash.png" border="0"></a>
				   <a href="/admin/history/id/<?php echo md5('idsalt'.$val['user_id']);?>" style="font-weight: bold;">History</a>
				</td></tr>
					<?php
				}
			}
			?>	     		
			</tbody></table>
			<div class="pagination">
		<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');?>
    	</div>

		</div>
      </div>  


   <div id="footer" class="round5" align="right">
      Copyright © 2013 MyLift Office
   </div>
